level: INFO
file: grpc_server.log
loggers:
  __main__: DEBUG
  src: DEBUG
  src.grpc_mod.service: INFO
  src.services: INFO
  src.db.database: INFO
  src.db.table: INFO
  httpcore.http11: ERROR
  httpx: ERROR
  httpcore: ERROR