[pytest]
asyncio_mode = auto
addopts = -m "not integration"  # per default run unit tests only
filterwarnings =
    ignore:The @wait_container_is_ready decorator is deprecated:DeprecationWarning
markers =
    integration: tests that require external services (e.g. containers)
    spicedb: tests that require a real SpiceDB instance