# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_mod.proto import activity_pb2 as activity__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in activity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActivityStatisticsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActivityHistory = channel.unary_stream(
                '/proto.ActivityStatisticsService/GetActivityHistory',
                request_serializer=activity__pb2.GetActivityHistoryRequest.SerializeToString,
                response_deserializer=activity__pb2.Activity.FromString,
                _registered_method=True)
        self.GetMostUsedActivity = channel.unary_stream(
                '/proto.ActivityStatisticsService/GetMostUsedActivity',
                request_serializer=activity__pb2.GetMostUsedActivityRequest.SerializeToString,
                response_deserializer=activity__pb2.ActivityScore.FromString,
                _registered_method=True)


class ActivityStatisticsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetActivityHistory(self, request, context):
        """Stream the activity log for everything the actor can view.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMostUsedActivity(self, request, context):
        """Stream aggregate note scores for everything the actor can view.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivityStatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActivityHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetActivityHistory,
                    request_deserializer=activity__pb2.GetActivityHistoryRequest.FromString,
                    response_serializer=activity__pb2.Activity.SerializeToString,
            ),
            'GetMostUsedActivity': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMostUsedActivity,
                    request_deserializer=activity__pb2.GetMostUsedActivityRequest.FromString,
                    response_serializer=activity__pb2.ActivityScore.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ActivityStatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ActivityStatisticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActivityStatisticsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActivityHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.ActivityStatisticsService/GetActivityHistory',
            activity__pb2.GetActivityHistoryRequest.SerializeToString,
            activity__pb2.Activity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMostUsedActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.ActivityStatisticsService/GetMostUsedActivity',
            activity__pb2.GetMostUsedActivityRequest.SerializeToString,
            activity__pb2.ActivityScore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
