"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _AccessedAs:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AccessedAsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AccessedAs.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ACCESSED_AS_UNSPECIFIED: _AccessedAs.ValueType  # 0
    ACCESSED_AS_USER: _AccessedAs.ValueType  # 1
    ACCESSED_AS_SYSTEM: _AccessedAs.ValueType  # 2

class AccessedAs(_AccessedAs, metaclass=_AccessedAsEnumTypeWrapper):
    """Discriminator for who was acting when an event happened."""

ACCESSED_AS_UNSPECIFIED: AccessedAs.ValueType  # 0
ACCESSED_AS_USER: AccessedAs.ValueType  # 1
ACCESSED_AS_SYSTEM: AccessedAs.ValueType  # 2
Global___AccessedAs: _TypeAlias = AccessedAs  # noqa: Y015

class _MostUsedAlgorithm:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MostUsedAlgorithmEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MostUsedAlgorithm.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MOST_USED_ALGORITHM_UNSPECIFIED: _MostUsedAlgorithm.ValueType  # 0
    MOST_USED_ALGORITHM_COUNT: _MostUsedAlgorithm.ValueType  # 1
    MOST_USED_ALGORITHM_LOG_COUNT: _MostUsedAlgorithm.ValueType  # 2

class MostUsedAlgorithm(_MostUsedAlgorithm, metaclass=_MostUsedAlgorithmEnumTypeWrapper):
    """Discriminator for the scoring strategy used in an ActivityScore."""

MOST_USED_ALGORITHM_UNSPECIFIED: MostUsedAlgorithm.ValueType  # 0
MOST_USED_ALGORITHM_COUNT: MostUsedAlgorithm.ValueType  # 1
MOST_USED_ALGORITHM_LOG_COUNT: MostUsedAlgorithm.ValueType  # 2
Global___MostUsedAlgorithm: _TypeAlias = MostUsedAlgorithm  # noqa: Y015

@_typing.final
class Activity(_message.Message):
    """One row from the activity log."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    ACTOR_ID_FIELD_NUMBER: _builtins.int
    ACCESSED_AS_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    NOTE_ID_FIELD_NUMBER: _builtins.int
    DIRECTORY_ID_FIELD_NUMBER: _builtins.int
    ROLE_ID_FIELD_NUMBER: _builtins.int
    AT_FIELD_NUMBER: _builtins.int
    METADATA_JSON_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    actor_id: _builtins.str
    accessed_as: Global___AccessedAs.ValueType
    action: _builtins.str
    note_id: _builtins.str
    directory_id: _builtins.str
    role_id: _builtins.str
    metadata_json: _builtins.str
    @_builtins.property
    def at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        actor_id: _builtins.str = ...,
        accessed_as: Global___AccessedAs.ValueType = ...,
        action: _builtins.str = ...,
        note_id: _builtins.str = ...,
        directory_id: _builtins.str = ...,
        role_id: _builtins.str = ...,
        at: _timestamp_pb2.Timestamp | None = ...,
        metadata_json: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["at", b"at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accessed_as", b"accessed_as", "action", b"action", "actor_id", b"actor_id", "at", b"at", "directory_id", b"directory_id", "id", b"id", "metadata_json", b"metadata_json", "note_id", b"note_id", "role_id", b"role_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Activity: _TypeAlias = Activity  # noqa: Y015

@_typing.final
class ActivityScore(_message.Message):
    """Aggregate score for one note plus its title and stripped content."""

    DESCRIPTOR: _descriptor.Descriptor

    NOTE_ID_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    STRIPPED_CONTENT_FIELD_NUMBER: _builtins.int
    note_id: _builtins.str
    score: _builtins.float
    title: _builtins.str
    stripped_content: _builtins.str
    def __init__(
        self,
        *,
        note_id: _builtins.str = ...,
        score: _builtins.float = ...,
        title: _builtins.str = ...,
        stripped_content: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["note_id", b"note_id", "score", b"score", "stripped_content", b"stripped_content", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivityScore: _TypeAlias = ActivityScore  # noqa: Y015

@_typing.final
class ActivityFilter(_message.Message):
    """History filter for both RPCs."""

    DESCRIPTOR: _descriptor.Descriptor

    NOTE_ID_FIELD_NUMBER: _builtins.int
    DIRECTORY_ID_FIELD_NUMBER: _builtins.int
    ACTOR_ID_FIELD_NUMBER: _builtins.int
    ROLE_ID_FIELD_NUMBER: _builtins.int
    ACCESSED_AS_FIELD_NUMBER: _builtins.int
    ACTIONS_FIELD_NUMBER: _builtins.int
    DAYS_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    UNIQUE_PER_DAY_FIELD_NUMBER: _builtins.int
    note_id: _builtins.str
    directory_id: _builtins.str
    actor_id: _builtins.str
    role_id: _builtins.str
    accessed_as: Global___AccessedAs.ValueType
    days: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    unique_per_day: _builtins.bool
    @_builtins.property
    def actions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        note_id: _builtins.str = ...,
        directory_id: _builtins.str = ...,
        actor_id: _builtins.str = ...,
        role_id: _builtins.str = ...,
        accessed_as: Global___AccessedAs.ValueType = ...,
        actions: _abc.Iterable[_builtins.str] | None = ...,
        days: _builtins.int | None = ...,
        limit: _builtins.int | None = ...,
        offset: _builtins.int | None = ...,
        unique_per_day: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_days", b"_days", "_limit", b"_limit", "_offset", b"_offset", "_unique_per_day", b"_unique_per_day", "days", b"days", "limit", b"limit", "offset", b"offset", "unique_per_day", b"unique_per_day"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_days", b"_days", "_limit", b"_limit", "_offset", b"_offset", "_unique_per_day", b"_unique_per_day", "accessed_as", b"accessed_as", "actions", b"actions", "actor_id", b"actor_id", "days", b"days", "directory_id", b"directory_id", "limit", b"limit", "note_id", b"note_id", "offset", b"offset", "role_id", b"role_id", "unique_per_day", b"unique_per_day"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__days: _TypeAlias = _typing.Literal["days"]  # noqa: Y015
    _WhichOneofArgType__days: _TypeAlias = _typing.Literal["_days", b"_days"]  # noqa: Y015
    _WhichOneofReturnType__limit: _TypeAlias = _typing.Literal["limit"]  # noqa: Y015
    _WhichOneofArgType__limit: _TypeAlias = _typing.Literal["_limit", b"_limit"]  # noqa: Y015
    _WhichOneofReturnType__offset: _TypeAlias = _typing.Literal["offset"]  # noqa: Y015
    _WhichOneofArgType__offset: _TypeAlias = _typing.Literal["_offset", b"_offset"]  # noqa: Y015
    _WhichOneofReturnType__unique_per_day: _TypeAlias = _typing.Literal["unique_per_day"]  # noqa: Y015
    _WhichOneofArgType__unique_per_day: _TypeAlias = _typing.Literal["_unique_per_day", b"_unique_per_day"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__days) -> _WhichOneofReturnType__days | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__limit) -> _WhichOneofReturnType__limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__offset) -> _WhichOneofReturnType__offset | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__unique_per_day) -> _WhichOneofReturnType__unique_per_day | None: ...

Global___ActivityFilter: _TypeAlias = ActivityFilter  # noqa: Y015

@_typing.final
class GetActivityHistoryRequest(_message.Message):
    """Request for GetActivityHistory."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    @_builtins.property
    def filter(self) -> Global___ActivityFilter: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        filter: Global___ActivityFilter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetActivityHistoryRequest: _TypeAlias = GetActivityHistoryRequest  # noqa: Y015

@_typing.final
class GetMostUsedActivityRequest(_message.Message):
    """Request for GetMostUsedActivity."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    ALGORITHM_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    algorithm: Global___MostUsedAlgorithm.ValueType
    limit: _builtins.int
    @_builtins.property
    def filter(self) -> Global___ActivityFilter: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        filter: Global___ActivityFilter | None = ...,
        algorithm: Global___MostUsedAlgorithm.ValueType = ...,
        limit: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_limit", b"_limit", "filter", b"filter", "limit", b"limit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_limit", b"_limit", "algorithm", b"algorithm", "filter", b"filter", "limit", b"limit", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__limit: _TypeAlias = _typing.Literal["limit"]  # noqa: Y015
    _WhichOneofArgType__limit: _TypeAlias = _typing.Literal["_limit", b"_limit"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__limit) -> _WhichOneofReturnType__limit | None: ...

Global___GetMostUsedActivityRequest: _TypeAlias = GetMostUsedActivityRequest  # noqa: Y015
