"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AttachmentMetadata(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    FILEPATH_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    SHA256_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    filename: _builtins.str
    filepath: _builtins.str
    content_type: _builtins.str
    size: _builtins.int
    sha256: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        filename: _builtins.str = ...,
        filepath: _builtins.str = ...,
        content_type: _builtins.str = ...,
        size: _builtins.int = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
        sha256: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "created_at", b"created_at", "filename", b"filename", "filepath", b"filepath", "key", b"key", "sha256", b"sha256", "size", b"size", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AttachmentMetadata: _TypeAlias = AttachmentMetadata  # noqa: Y015

@_typing.final
class Attachment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METADATA_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    content: _builtins.bytes
    @_builtins.property
    def metadata(self) -> Global___AttachmentMetadata: ...
    def __init__(
        self,
        *,
        metadata: Global___AttachmentMetadata | None = ...,
        content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "metadata", b"metadata"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Attachment: _TypeAlias = Attachment  # noqa: Y015

@_typing.final
class PostAttachmentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FILENAME_FIELD_NUMBER: _builtins.int
    FILEPATH_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    filename: _builtins.str
    filepath: _builtins.str
    content_type: _builtins.str
    content: _builtins.bytes
    user_id: _builtins.str
    def __init__(
        self,
        *,
        filename: _builtins.str = ...,
        filepath: _builtins.str = ...,
        content_type: _builtins.str = ...,
        content: _builtins.bytes = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "content_type", b"content_type", "filename", b"filename", "filepath", b"filepath", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PostAttachmentRequest: _TypeAlias = PostAttachmentRequest  # noqa: Y015

@_typing.final
class PostAttachmentLinkRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ATTACHMENT_KEY_FIELD_NUMBER: _builtins.int
    NOTE_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    attachment_key: _builtins.str
    note_id: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        attachment_key: _builtins.str = ...,
        note_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attachment_key", b"attachment_key", "note_id", b"note_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PostAttachmentLinkRequest: _TypeAlias = PostAttachmentLinkRequest  # noqa: Y015

@_typing.final
class DeleteAttachmentLinkRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ATTACHMENT_KEY_FIELD_NUMBER: _builtins.int
    NOTE_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    attachment_key: _builtins.str
    note_id: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        attachment_key: _builtins.str = ...,
        note_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attachment_key", b"attachment_key", "note_id", b"note_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteAttachmentLinkRequest: _TypeAlias = DeleteAttachmentLinkRequest  # noqa: Y015

@_typing.final
class GetAttachmentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAttachmentRequest: _TypeAlias = GetAttachmentRequest  # noqa: Y015

@_typing.final
class GetAttachmentMetadataRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAttachmentMetadataRequest: _TypeAlias = GetAttachmentMetadataRequest  # noqa: Y015

@_typing.final
class DeleteAttachmentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteAttachmentRequest: _TypeAlias = DeleteAttachmentRequest  # noqa: Y015

@_typing.final
class DeleteAttachmentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteAttachmentResponse: _TypeAlias = DeleteAttachmentResponse  # noqa: Y015
