# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc_mod.proto import attachments_pb2 as src_dot_grpc__mod_dot_proto_dot_attachments__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc_mod/proto/attachments_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttachmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostAttachment = channel.unary_unary(
                '/proto.AttachmentService/PostAttachment',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.PostAttachmentRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.Attachment.FromString,
                _registered_method=True)
        self.GetAttachment = channel.unary_unary(
                '/proto.AttachmentService/GetAttachment',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.GetAttachmentRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.Attachment.FromString,
                _registered_method=True)
        self.GetAttachmentMetadata = channel.unary_unary(
                '/proto.AttachmentService/GetAttachmentMetadata',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.GetAttachmentMetadataRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.AttachmentMetadata.FromString,
                _registered_method=True)
        self.DeleteAttachment = channel.unary_unary(
                '/proto.AttachmentService/DeleteAttachment',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentResponse.FromString,
                _registered_method=True)
        self.PostAttachmentLink = channel.unary_unary(
                '/proto.AttachmentService/PostAttachmentLink',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.PostAttachmentLinkRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteAttachmentLink = channel.unary_unary(
                '/proto.AttachmentService/DeleteAttachmentLink',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentLinkRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AttachmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostAttachment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttachment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttachmentMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAttachment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostAttachmentLink(self, request, context):
        """either works -> no return or fails completely with an error, so no need for a response message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAttachmentLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttachmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.PostAttachment,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.PostAttachmentRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.Attachment.SerializeToString,
            ),
            'GetAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttachment,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.GetAttachmentRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.Attachment.SerializeToString,
            ),
            'GetAttachmentMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttachmentMetadata,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.GetAttachmentMetadataRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.AttachmentMetadata.SerializeToString,
            ),
            'DeleteAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAttachment,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentResponse.SerializeToString,
            ),
            'PostAttachmentLink': grpc.unary_unary_rpc_method_handler(
                    servicer.PostAttachmentLink,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.PostAttachmentLinkRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteAttachmentLink': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAttachmentLink,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentLinkRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AttachmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.AttachmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttachmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AttachmentService/PostAttachment',
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.PostAttachmentRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.Attachment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AttachmentService/GetAttachment',
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.GetAttachmentRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.Attachment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttachmentMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AttachmentService/GetAttachmentMetadata',
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.GetAttachmentMetadataRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.AttachmentMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AttachmentService/DeleteAttachment',
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostAttachmentLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AttachmentService/PostAttachmentLink',
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.PostAttachmentLinkRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAttachmentLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AttachmentService/DeleteAttachmentLink',
            src_dot_grpc__mod_dot_proto_dot_attachments__pb2.DeleteAttachmentLinkRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
