# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc_mod.proto import auth_pb2 as src_dot_grpc__mod_dot_proto_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc_mod/proto/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserAuth = channel.unary_unary(
                '/proto.AuthService/GetUserAuth',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.GetUserAuthRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.GetUserAuthResponse.FromString,
                _registered_method=True)
        self.CreateUserAuth = channel.unary_unary(
                '/proto.AuthService/CreateUserAuth',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.CreateUserAuthRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.CreateUserAuthResponse.FromString,
                _registered_method=True)
        self.UpdateUserAuth = channel.unary_unary(
                '/proto.AuthService/UpdateUserAuth',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdateUserAuthRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdateUserAuthResponse.FromString,
                _registered_method=True)
        self.FindCredentialByProvider = channel.unary_unary(
                '/proto.AuthService/FindCredentialByProvider',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindCredentialByProviderRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindCredentialByProviderResponse.FromString,
                _registered_method=True)
        self.FindPasskey = channel.unary_unary(
                '/proto.AuthService/FindPasskey',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindPasskeyRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindPasskeyResponse.FromString,
                _registered_method=True)
        self.ListPasskeys = channel.unary_unary(
                '/proto.AuthService/ListPasskeys',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListPasskeysRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListPasskeysResponse.FromString,
                _registered_method=True)
        self.UpdatePasskeyCounter = channel.unary_unary(
                '/proto.AuthService/UpdatePasskeyCounter',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdatePasskeyCounterRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdatePasskeyCounterResponse.FromString,
                _registered_method=True)
        self.RegisterPasskey = channel.unary_unary(
                '/proto.AuthService/RegisterPasskey',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.RegisterPasskeyRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.RegisterPasskeyResponse.FromString,
                _registered_method=True)
        self.RevokePasskey = channel.unary_unary(
                '/proto.AuthService/RevokePasskey',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.RevokePasskeyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.LinkCredential = channel.unary_unary(
                '/proto.AuthService/LinkCredential',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.LinkCredentialRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.LinkCredentialResponse.FromString,
                _registered_method=True)
        self.UnlinkCredential = channel.unary_unary(
                '/proto.AuthService/UnlinkCredential',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UnlinkCredentialRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListLinkedCredentials = channel.unary_unary(
                '/proto.AuthService/ListLinkedCredentials',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListLinkedCredentialsRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListLinkedCredentialsResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUserAuth(self, request, context):
        """user lookup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindCredentialByProvider(self, request, context):
        """credential lookup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPasskey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPasskeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePasskeyCounter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPasskey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokePasskey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkCredential(self, request, context):
        """account linking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLinkedCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAuth,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.GetUserAuthRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.GetUserAuthResponse.SerializeToString,
            ),
            'CreateUserAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserAuth,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.CreateUserAuthRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.CreateUserAuthResponse.SerializeToString,
            ),
            'UpdateUserAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserAuth,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdateUserAuthRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdateUserAuthResponse.SerializeToString,
            ),
            'FindCredentialByProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.FindCredentialByProvider,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindCredentialByProviderRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindCredentialByProviderResponse.SerializeToString,
            ),
            'FindPasskey': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPasskey,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindPasskeyRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindPasskeyResponse.SerializeToString,
            ),
            'ListPasskeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPasskeys,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListPasskeysRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListPasskeysResponse.SerializeToString,
            ),
            'UpdatePasskeyCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePasskeyCounter,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdatePasskeyCounterRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdatePasskeyCounterResponse.SerializeToString,
            ),
            'RegisterPasskey': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPasskey,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.RegisterPasskeyRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.RegisterPasskeyResponse.SerializeToString,
            ),
            'RevokePasskey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokePasskey,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.RevokePasskeyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'LinkCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkCredential,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.LinkCredentialRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.LinkCredentialResponse.SerializeToString,
            ),
            'UnlinkCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkCredential,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.UnlinkCredentialRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListLinkedCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLinkedCredentials,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListLinkedCredentialsRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListLinkedCredentialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/GetUserAuth',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.GetUserAuthRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.GetUserAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/CreateUserAuth',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.CreateUserAuthRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.CreateUserAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/UpdateUserAuth',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdateUserAuthRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdateUserAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindCredentialByProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/FindCredentialByProvider',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindCredentialByProviderRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindCredentialByProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPasskey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/FindPasskey',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindPasskeyRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.FindPasskeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPasskeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/ListPasskeys',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListPasskeysRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListPasskeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePasskeyCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/UpdatePasskeyCounter',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdatePasskeyCounterRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.UpdatePasskeyCounterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPasskey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/RegisterPasskey',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.RegisterPasskeyRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.RegisterPasskeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokePasskey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/RevokePasskey',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.RevokePasskeyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/LinkCredential',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.LinkCredentialRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.LinkCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/UnlinkCredential',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.UnlinkCredentialRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLinkedCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AuthService/ListLinkedCredentials',
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListLinkedCredentialsRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_auth__pb2.ListLinkedCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
