"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _CredentialKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CredentialKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CredentialKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CREDENTIAL_KIND_UNSPECIFIED: _CredentialKind.ValueType  # 0
    CREDENTIAL_KIND_DISCORD: _CredentialKind.ValueType  # 1
    CREDENTIAL_KIND_PASSWORD: _CredentialKind.ValueType  # 2
    CREDENTIAL_KIND_PASSKEY: _CredentialKind.ValueType  # 3
    CREDENTIAL_KIND_GOOGLE: _CredentialKind.ValueType  # 4

class CredentialKind(_CredentialKind, metaclass=_CredentialKindEnumTypeWrapper):
    """Auth proto.

    Layering:
    - The browser does not talk to gRPC. REST (`WerSu-Rest`) is the
      HTTP edge and runs the WebAuthn ceremony (challenge generation,
      attestation/assertion verification) using `go-webauthn`. It also
      handles password hashing, rate limiting, JWT issuance, and email
      delivery.
    - gRPC is the source of truth for users and credentials. REST
      calls into this service to look up credentials, persist public
      keys, and bump counters. REST does not write to the auth tables
      directly.
    - There is no session table on the backend. Every request that
      reaches gRPC is trusted because the REST middleware has already
      verified a JWT or session.
    """

CREDENTIAL_KIND_UNSPECIFIED: CredentialKind.ValueType  # 0
CREDENTIAL_KIND_DISCORD: CredentialKind.ValueType  # 1
CREDENTIAL_KIND_PASSWORD: CredentialKind.ValueType  # 2
CREDENTIAL_KIND_PASSKEY: CredentialKind.ValueType  # 3
CREDENTIAL_KIND_GOOGLE: CredentialKind.ValueType  # 4
Global___CredentialKind: _TypeAlias = CredentialKind  # noqa: Y015

@_typing.final
class UserAuth(_message.Message):
    """A user as exposed to the auth layer."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    EMAIL_VERIFIED_AT_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    AVATAR_URL_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    email: _builtins.str
    username: _builtins.str
    """Username is optional; empty string means the user has not set one."""
    is_active: _builtins.bool
    avatar_url: _builtins.str
    """Absolute URL to the user's avatar. Empty string means none
    is configured. The REST controller maps this to JSON null
    on the frontend.
    """
    @_builtins.property
    def email_verified_at(self) -> _timestamp_pb2.Timestamp:
        """Zero timestamp means the email has not been verified yet."""

    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        email: _builtins.str = ...,
        username: _builtins.str = ...,
        email_verified_at: _timestamp_pb2.Timestamp | None = ...,
        is_active: _builtins.bool = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        avatar_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "email_verified_at", b"email_verified_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar_url", b"avatar_url", "created_at", b"created_at", "email", b"email", "email_verified_at", b"email_verified_at", "id", b"id", "is_active", b"is_active", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UserAuth: _TypeAlias = UserAuth  # noqa: Y015

@_typing.final
class Credential(_message.Message):
    """A stored credential. Exactly one of the `payload` oneof fields is
    populated, enforced by the service layer. The `kind` enum tells
    REST which one to read.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    LAST_USED_AT_FIELD_NUMBER: _builtins.int
    DISCORD_ID_FIELD_NUMBER: _builtins.int
    PASSWORD_HASH_FIELD_NUMBER: _builtins.int
    PASSKEY_ID_FIELD_NUMBER: _builtins.int
    GOOGLE_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    user_id: _builtins.str
    kind: Global___CredentialKind.ValueType
    discord_id: _builtins.str
    """kind = DISCORD"""
    password_hash: _builtins.str
    """kind = PASSWORD -- argon2id encoded string"""
    passkey_id: _builtins.str
    """kind = PASSKEY -- points at the row in `passkeys` table"""
    google_id: _builtins.str
    """kind = GOOGLE -- Google's stable user id from the `sub` claim"""
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def last_used_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        kind: Global___CredentialKind.ValueType = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        last_used_at: _timestamp_pb2.Timestamp | None = ...,
        discord_id: _builtins.str = ...,
        password_hash: _builtins.str = ...,
        passkey_id: _builtins.str = ...,
        google_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "discord_id", b"discord_id", "google_id", b"google_id", "last_used_at", b"last_used_at", "passkey_id", b"passkey_id", "password_hash", b"password_hash", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "discord_id", b"discord_id", "google_id", b"google_id", "id", b"id", "kind", b"kind", "last_used_at", b"last_used_at", "passkey_id", b"passkey_id", "password_hash", b"password_hash", "payload", b"payload", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["discord_id", "password_hash", "passkey_id", "google_id"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___Credential: _TypeAlias = Credential  # noqa: Y015

@_typing.final
class Passkey(_message.Message):
    """A stored WebAuthn passkey (public-key credential).

    The private key never leaves the user's device. The `public_key`
    field holds the COSE-encoded public key produced by the
    authenticator at registration time. `sign_count` is updated on
    every successful login and must strictly increase; a non-monotonic
    counter suggests an authenticator clone.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    CREDENTIAL_ID_FIELD_NUMBER: _builtins.int
    PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    SIGN_COUNT_FIELD_NUMBER: _builtins.int
    TRANSPORTS_FIELD_NUMBER: _builtins.int
    AAGUID_FIELD_NUMBER: _builtins.int
    BACKUP_ELIGIBLE_FIELD_NUMBER: _builtins.int
    BACKUP_STATE_FIELD_NUMBER: _builtins.int
    USER_VERIFIED_FIELD_NUMBER: _builtins.int
    FRIENDLY_NAME_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    LAST_USED_AT_FIELD_NUMBER: _builtins.int
    REVOKED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    user_id: _builtins.str
    credential_id: _builtins.bytes
    public_key: _builtins.bytes
    sign_count: _builtins.int
    aaguid: _builtins.bytes
    backup_eligible: _builtins.bool
    backup_state: _builtins.bool
    user_verified: _builtins.bool
    friendly_name: _builtins.str
    @_builtins.property
    def transports(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def last_used_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def revoked_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        credential_id: _builtins.bytes = ...,
        public_key: _builtins.bytes = ...,
        sign_count: _builtins.int = ...,
        transports: _abc.Iterable[_builtins.str] | None = ...,
        aaguid: _builtins.bytes = ...,
        backup_eligible: _builtins.bool = ...,
        backup_state: _builtins.bool = ...,
        user_verified: _builtins.bool = ...,
        friendly_name: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        last_used_at: _timestamp_pb2.Timestamp | None = ...,
        revoked_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "last_used_at", b"last_used_at", "revoked_at", b"revoked_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aaguid", b"aaguid", "backup_eligible", b"backup_eligible", "backup_state", b"backup_state", "created_at", b"created_at", "credential_id", b"credential_id", "friendly_name", b"friendly_name", "id", b"id", "last_used_at", b"last_used_at", "public_key", b"public_key", "revoked_at", b"revoked_at", "sign_count", b"sign_count", "transports", b"transports", "user_id", b"user_id", "user_verified", b"user_verified"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Passkey: _TypeAlias = Passkey  # noqa: Y015

@_typing.final
class GetUserAuthRequest(_message.Message):
    """Lookup a user by id/email/discord id
    Often used by frontend: useUser() hook resolves to this.
    REST takes user id from session, and checks against this endpoint
    if information is correct.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    DISCORD_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    email: _builtins.str
    discord_id: _builtins.int
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        email: _builtins.str = ...,
        discord_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["discord_id", b"discord_id", "email", b"email", "identifier", b"identifier", "user_id", b"user_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["discord_id", b"discord_id", "email", b"email", "identifier", b"identifier", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_identifier: _TypeAlias = _typing.Literal["user_id", "email", "discord_id"]  # noqa: Y015
    _WhichOneofArgType_identifier: _TypeAlias = _typing.Literal["identifier", b"identifier"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_identifier) -> _WhichOneofReturnType_identifier | None: ...

Global___GetUserAuthRequest: _TypeAlias = GetUserAuthRequest  # noqa: Y015

@_typing.final
class GetUserAuthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___UserAuth: ...
    def __init__(
        self,
        *,
        user: Global___UserAuth | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserAuthResponse: _TypeAlias = GetUserAuthResponse  # noqa: Y015

@_typing.final
class CreateUserAuthRequest(_message.Message):
    """Create a user (email + password signup). Returns
    ALREADY_EXISTS if a user with the email already exists.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EMAIL_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    PASSWORD_HASH_FIELD_NUMBER: _builtins.int
    AVATAR_URL_FIELD_NUMBER: _builtins.int
    email: _builtins.str
    username: _builtins.str
    password_hash: _builtins.str
    avatar_url: _builtins.str
    """Optional. Absolute URL to the user's avatar (resolved by the
    REST controller via Discord/Google/Gravatar fallbacks). Empty
    string means none. The frontend maps empty to JSON null.
    """
    def __init__(
        self,
        *,
        email: _builtins.str = ...,
        username: _builtins.str = ...,
        password_hash: _builtins.str = ...,
        avatar_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar_url", b"avatar_url", "email", b"email", "password_hash", b"password_hash", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateUserAuthRequest: _TypeAlias = CreateUserAuthRequest  # noqa: Y015

@_typing.final
class CreateUserAuthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___UserAuth: ...
    def __init__(
        self,
        *,
        user: Global___UserAuth | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateUserAuthResponse: _TypeAlias = CreateUserAuthResponse  # noqa: Y015

@_typing.final
class UpdateUserAuthRequest(_message.Message):
    """Update mutable fields on an existing user. Each field is a
    tri-state: omitted (leave unchanged), `_set` populated (write the
    value), or `_clear` populated (set the column to NULL). Used for
    username/email changes and `email_verified_at`.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    REQUESTER_ID_FIELD_NUMBER: _builtins.int
    USERNAME_SET_FIELD_NUMBER: _builtins.int
    USERNAME_CLEAR_FIELD_NUMBER: _builtins.int
    EMAIL_SET_FIELD_NUMBER: _builtins.int
    EMAIL_CLEAR_FIELD_NUMBER: _builtins.int
    EMAIL_VERIFIED_AT_SET_FIELD_NUMBER: _builtins.int
    EMAIL_VERIFIED_AT_CLEAR_FIELD_NUMBER: _builtins.int
    AVATAR_URL_SET_FIELD_NUMBER: _builtins.int
    AVATAR_URL_CLEAR_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    requester_id: _builtins.str
    """the actor on which we will check permissions"""
    username_set: _builtins.str
    email_set: _builtins.str
    avatar_url_set: _builtins.str
    @_builtins.property
    def username_clear(self) -> _empty_pb2.Empty: ...
    @_builtins.property
    def email_clear(self) -> _empty_pb2.Empty: ...
    @_builtins.property
    def email_verified_at_set(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def email_verified_at_clear(self) -> _empty_pb2.Empty: ...
    @_builtins.property
    def avatar_url_clear(self) -> _empty_pb2.Empty: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        requester_id: _builtins.str = ...,
        username_set: _builtins.str = ...,
        username_clear: _empty_pb2.Empty | None = ...,
        email_set: _builtins.str = ...,
        email_clear: _empty_pb2.Empty | None = ...,
        email_verified_at_set: _timestamp_pb2.Timestamp | None = ...,
        email_verified_at_clear: _empty_pb2.Empty | None = ...,
        avatar_url_set: _builtins.str = ...,
        avatar_url_clear: _empty_pb2.Empty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["avatar_url_change", b"avatar_url_change", "avatar_url_clear", b"avatar_url_clear", "avatar_url_set", b"avatar_url_set", "email_change", b"email_change", "email_clear", b"email_clear", "email_set", b"email_set", "email_verified_at_clear", b"email_verified_at_clear", "email_verified_at_set", b"email_verified_at_set", "email_verified_change", b"email_verified_change", "username_change", b"username_change", "username_clear", b"username_clear", "username_set", b"username_set"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar_url_change", b"avatar_url_change", "avatar_url_clear", b"avatar_url_clear", "avatar_url_set", b"avatar_url_set", "email_change", b"email_change", "email_clear", b"email_clear", "email_set", b"email_set", "email_verified_at_clear", b"email_verified_at_clear", "email_verified_at_set", b"email_verified_at_set", "email_verified_change", b"email_verified_change", "requester_id", b"requester_id", "user_id", b"user_id", "username_change", b"username_change", "username_clear", b"username_clear", "username_set", b"username_set"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_avatar_url_change: _TypeAlias = _typing.Literal["avatar_url_set", "avatar_url_clear"]  # noqa: Y015
    _WhichOneofArgType_avatar_url_change: _TypeAlias = _typing.Literal["avatar_url_change", b"avatar_url_change"]  # noqa: Y015
    _WhichOneofReturnType_email_change: _TypeAlias = _typing.Literal["email_set", "email_clear"]  # noqa: Y015
    _WhichOneofArgType_email_change: _TypeAlias = _typing.Literal["email_change", b"email_change"]  # noqa: Y015
    _WhichOneofReturnType_email_verified_change: _TypeAlias = _typing.Literal["email_verified_at_set", "email_verified_at_clear"]  # noqa: Y015
    _WhichOneofArgType_email_verified_change: _TypeAlias = _typing.Literal["email_verified_change", b"email_verified_change"]  # noqa: Y015
    _WhichOneofReturnType_username_change: _TypeAlias = _typing.Literal["username_set", "username_clear"]  # noqa: Y015
    _WhichOneofArgType_username_change: _TypeAlias = _typing.Literal["username_change", b"username_change"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_avatar_url_change) -> _WhichOneofReturnType_avatar_url_change | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_email_change) -> _WhichOneofReturnType_email_change | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_email_verified_change) -> _WhichOneofReturnType_email_verified_change | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_username_change) -> _WhichOneofReturnType_username_change | None: ...

Global___UpdateUserAuthRequest: _TypeAlias = UpdateUserAuthRequest  # noqa: Y015

@_typing.final
class UpdateUserAuthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> Global___UserAuth: ...
    def __init__(
        self,
        *,
        user: Global___UserAuth | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateUserAuthResponse: _TypeAlias = UpdateUserAuthResponse  # noqa: Y015

@_typing.final
class FindCredentialByProviderRequest(_message.Message):
    """Search a user by email/discord id/google id"""

    DESCRIPTOR: _descriptor.Descriptor

    DISCORD_ID_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    GOOGLE_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    discord_id: _builtins.int
    email: _builtins.str
    google_id: _builtins.str
    kind: Global___CredentialKind.ValueType
    def __init__(
        self,
        *,
        discord_id: _builtins.int = ...,
        email: _builtins.str = ...,
        google_id: _builtins.str = ...,
        kind: Global___CredentialKind.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["discord_id", b"discord_id", "email", b"email", "google_id", b"google_id", "identifier", b"identifier"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["discord_id", b"discord_id", "email", b"email", "google_id", b"google_id", "identifier", b"identifier", "kind", b"kind"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_identifier: _TypeAlias = _typing.Literal["discord_id", "email", "google_id"]  # noqa: Y015
    _WhichOneofArgType_identifier: _TypeAlias = _typing.Literal["identifier", b"identifier"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_identifier) -> _WhichOneofReturnType_identifier | None: ...

Global___FindCredentialByProviderRequest: _TypeAlias = FindCredentialByProviderRequest  # noqa: Y015

@_typing.final
class FindCredentialByProviderResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CREDENTIAL_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def credential(self) -> Global___Credential: ...
    @_builtins.property
    def user(self) -> Global___UserAuth: ...
    def __init__(
        self,
        *,
        credential: Global___Credential | None = ...,
        user: Global___UserAuth | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["credential", b"credential", "user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["credential", b"credential", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FindCredentialByProviderResponse: _TypeAlias = FindCredentialByProviderResponse  # noqa: Y015

@_typing.final
class FindPasskeyRequest(_message.Message):
    """Look up a passkey by its WebAuthn credential id. REST calls
    this with the `id` from `navigator.credentials.get()` so it
    can do the signature verification with the right public key.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CREDENTIAL_ID_FIELD_NUMBER: _builtins.int
    credential_id: _builtins.bytes
    def __init__(
        self,
        *,
        credential_id: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["credential_id", b"credential_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FindPasskeyRequest: _TypeAlias = FindPasskeyRequest  # noqa: Y015

@_typing.final
class FindPasskeyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSKEY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def passkey(self) -> Global___Passkey: ...
    def __init__(
        self,
        *,
        passkey: Global___Passkey | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["passkey", b"passkey"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["passkey", b"passkey"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FindPasskeyResponse: _TypeAlias = FindPasskeyResponse  # noqa: Y015

@_typing.final
class ListPasskeysRequest(_message.Message):
    """List a user's passkeys for the settings page (with a friendly
    label, last-used date, and a way to revoke each).
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    INCLUDE_REVOKED_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    include_revoked: _builtins.bool
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        include_revoked: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["include_revoked", b"include_revoked", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPasskeysRequest: _TypeAlias = ListPasskeysRequest  # noqa: Y015

@_typing.final
class ListPasskeysResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSKEYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def passkeys(self) -> _containers.RepeatedCompositeFieldContainer[Global___Passkey]: ...
    def __init__(
        self,
        *,
        passkeys: _abc.Iterable[Global___Passkey] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["passkeys", b"passkeys"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPasskeysResponse: _TypeAlias = ListPasskeysResponse  # noqa: Y015

@_typing.final
class UpdatePasskeyCounterRequest(_message.Message):
    """Bump the sign counter after a successful assertion. REST
    verifies the signature first, then calls this. The service
    returns FAILED_PRECONDITION if the new counter is not strictly
    greater than the stored one (cloned authenticator).
    """

    DESCRIPTOR: _descriptor.Descriptor

    PASSKEY_ID_FIELD_NUMBER: _builtins.int
    NEW_SIGN_COUNT_FIELD_NUMBER: _builtins.int
    passkey_id: _builtins.str
    new_sign_count: _builtins.int
    def __init__(
        self,
        *,
        passkey_id: _builtins.str = ...,
        new_sign_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["new_sign_count", b"new_sign_count", "passkey_id", b"passkey_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdatePasskeyCounterRequest: _TypeAlias = UpdatePasskeyCounterRequest  # noqa: Y015

@_typing.final
class UpdatePasskeyCounterResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSKEY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def passkey(self) -> Global___Passkey: ...
    def __init__(
        self,
        *,
        passkey: Global___Passkey | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["passkey", b"passkey"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["passkey", b"passkey"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdatePasskeyCounterResponse: _TypeAlias = UpdatePasskeyCounterResponse  # noqa: Y015

@_typing.final
class RegisterPasskeyRequest(_message.Message):
    """Store a new passkey after REST has verified the attestation.
    `credential_id` is the raw bytes from the authenticator.
    `public_key` is the COSE-encoded public key extracted from the
    attestation authData. The service layer is responsible for
    storing both in their native byte form -- they are not reshaped.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    REQUESTER_ID_FIELD_NUMBER: _builtins.int
    CREDENTIAL_ID_FIELD_NUMBER: _builtins.int
    PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    TRANSPORTS_FIELD_NUMBER: _builtins.int
    AAGUID_FIELD_NUMBER: _builtins.int
    BACKUP_ELIGIBLE_FIELD_NUMBER: _builtins.int
    BACKUP_STATE_FIELD_NUMBER: _builtins.int
    USER_VERIFIED_FIELD_NUMBER: _builtins.int
    FRIENDLY_NAME_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    requester_id: _builtins.str
    """actor on which we will check permissions"""
    credential_id: _builtins.bytes
    public_key: _builtins.bytes
    aaguid: _builtins.bytes
    backup_eligible: _builtins.bool
    backup_state: _builtins.bool
    user_verified: _builtins.bool
    friendly_name: _builtins.str
    @_builtins.property
    def transports(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        requester_id: _builtins.str = ...,
        credential_id: _builtins.bytes = ...,
        public_key: _builtins.bytes = ...,
        transports: _abc.Iterable[_builtins.str] | None = ...,
        aaguid: _builtins.bytes = ...,
        backup_eligible: _builtins.bool = ...,
        backup_state: _builtins.bool = ...,
        user_verified: _builtins.bool = ...,
        friendly_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aaguid", b"aaguid", "backup_eligible", b"backup_eligible", "backup_state", b"backup_state", "credential_id", b"credential_id", "friendly_name", b"friendly_name", "public_key", b"public_key", "requester_id", b"requester_id", "transports", b"transports", "user_id", b"user_id", "user_verified", b"user_verified"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterPasskeyRequest: _TypeAlias = RegisterPasskeyRequest  # noqa: Y015

@_typing.final
class RegisterPasskeyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSKEY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def passkey(self) -> Global___Passkey: ...
    def __init__(
        self,
        *,
        passkey: Global___Passkey | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["passkey", b"passkey"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["passkey", b"passkey"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterPasskeyResponse: _TypeAlias = RegisterPasskeyResponse  # noqa: Y015

@_typing.final
class RevokePasskeyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSKEY_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    REQUESTER_ID_FIELD_NUMBER: _builtins.int
    passkey_id: _builtins.str
    user_id: _builtins.str
    requester_id: _builtins.str
    def __init__(
        self,
        *,
        passkey_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        requester_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["passkey_id", b"passkey_id", "requester_id", b"requester_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RevokePasskeyRequest: _TypeAlias = RevokePasskeyRequest  # noqa: Y015

@_typing.final
class LinkCredentialRequest(_message.Message):
    """Account Linking: Attach a new credential to an existing user (Passkey
    Discord OAuth, Google OAuth, or password)

    `kind` selects which payload field is populated. Exactly one of
    `discord_id`, `password_hash`, `passkey_id`, or `google_id` must
    be set. Returns ALREADY_EXISTS if the user already has a
    credential of that kind (with the exception of passkey, which
    can have many).
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    REQUESTER_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    DISCORD_ID_FIELD_NUMBER: _builtins.int
    PASSWORD_HASH_FIELD_NUMBER: _builtins.int
    PASSKEY_ID_FIELD_NUMBER: _builtins.int
    GOOGLE_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    requester_id: _builtins.str
    kind: Global___CredentialKind.ValueType
    discord_id: _builtins.str
    password_hash: _builtins.str
    passkey_id: _builtins.str
    google_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        requester_id: _builtins.str = ...,
        kind: Global___CredentialKind.ValueType = ...,
        discord_id: _builtins.str = ...,
        password_hash: _builtins.str = ...,
        passkey_id: _builtins.str = ...,
        google_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["discord_id", b"discord_id", "google_id", b"google_id", "passkey_id", b"passkey_id", "password_hash", b"password_hash", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["discord_id", b"discord_id", "google_id", b"google_id", "kind", b"kind", "passkey_id", b"passkey_id", "password_hash", b"password_hash", "payload", b"payload", "requester_id", b"requester_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["discord_id", "password_hash", "passkey_id", "google_id"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___LinkCredentialRequest: _TypeAlias = LinkCredentialRequest  # noqa: Y015

@_typing.final
class LinkCredentialResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CREDENTIAL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def credential(self) -> Global___Credential: ...
    def __init__(
        self,
        *,
        credential: Global___Credential | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["credential", b"credential"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["credential", b"credential"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LinkCredentialResponse: _TypeAlias = LinkCredentialResponse  # noqa: Y015

@_typing.final
class UnlinkCredentialRequest(_message.Message):
    """Unlink a credential. Removing the last credential should raise"""

    DESCRIPTOR: _descriptor.Descriptor

    CREDENTIAL_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    REQUESTER_ID_FIELD_NUMBER: _builtins.int
    credential_id: _builtins.str
    user_id: _builtins.str
    requester_id: _builtins.str
    """the actor on which we will check permissions"""
    def __init__(
        self,
        *,
        credential_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        requester_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["credential_id", b"credential_id", "requester_id", b"requester_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnlinkCredentialRequest: _TypeAlias = UnlinkCredentialRequest  # noqa: Y015

@_typing.final
class ListLinkedCredentialsRequest(_message.Message):
    """Summary of every credential linked to a user (Google, Discord, Passkey, Password)"""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListLinkedCredentialsRequest: _TypeAlias = ListLinkedCredentialsRequest  # noqa: Y015

@_typing.final
class ListLinkedCredentialsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CREDENTIALS_FIELD_NUMBER: _builtins.int
    PASSKEYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def credentials(self) -> _containers.RepeatedCompositeFieldContainer[Global___Credential]: ...
    @_builtins.property
    def passkeys(self) -> _containers.RepeatedCompositeFieldContainer[Global___Passkey]: ...
    def __init__(
        self,
        *,
        credentials: _abc.Iterable[Global___Credential] | None = ...,
        passkeys: _abc.Iterable[Global___Passkey] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["credentials", b"credentials", "passkeys", b"passkeys"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListLinkedCredentialsResponse: _TypeAlias = ListLinkedCredentialsResponse  # noqa: Y015
