"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _PermissionObjectType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PermissionObjectTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PermissionObjectType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PERMISSION_OBJECT_TYPE_UNSPECIFIED: _PermissionObjectType.ValueType  # 0
    PERMISSION_OBJECT_TYPE_NOTE: _PermissionObjectType.ValueType  # 1
    PERMISSION_OBJECT_TYPE_DIRECTORY: _PermissionObjectType.ValueType  # 2
    PERMISSION_OBJECT_TYPE_USER: _PermissionObjectType.ValueType  # 3
    PERMISSION_OBJECT_TYPE_ATTACHMENT: _PermissionObjectType.ValueType  # 4

class PermissionObjectType(_PermissionObjectType, metaclass=_PermissionObjectTypeEnumTypeWrapper): ...

PERMISSION_OBJECT_TYPE_UNSPECIFIED: PermissionObjectType.ValueType  # 0
PERMISSION_OBJECT_TYPE_NOTE: PermissionObjectType.ValueType  # 1
PERMISSION_OBJECT_TYPE_DIRECTORY: PermissionObjectType.ValueType  # 2
PERMISSION_OBJECT_TYPE_USER: PermissionObjectType.ValueType  # 3
PERMISSION_OBJECT_TYPE_ATTACHMENT: PermissionObjectType.ValueType  # 4
Global___PermissionObjectType: _TypeAlias = PermissionObjectType  # noqa: Y015

@_typing.final
class GetNoteRequest(_message.Message):
    """Request for getting a note by id"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetNoteRequest: _TypeAlias = GetNoteRequest  # noqa: Y015

@_typing.final
class GetSearchNotesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SearchType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SearchTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[GetSearchNotesRequest._SearchType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Undefined: GetSearchNotesRequest._SearchType.ValueType  # 0
        """default"""
        NoSearch: GetSearchNotesRequest._SearchType.ValueType  # 1
        """latest notes"""
        FullTextTitle: GetSearchNotesRequest._SearchType.ValueType  # 2
        """exact match search"""
        Fuzzy: GetSearchNotesRequest._SearchType.ValueType  # 3
        """typo tolerant search"""
        Context: GetSearchNotesRequest._SearchType.ValueType  # 4
        """semantic search using embeddings"""

    class SearchType(_SearchType, metaclass=_SearchTypeEnumTypeWrapper): ...
    Undefined: GetSearchNotesRequest.SearchType.ValueType  # 0
    """default"""
    NoSearch: GetSearchNotesRequest.SearchType.ValueType  # 1
    """latest notes"""
    FullTextTitle: GetSearchNotesRequest.SearchType.ValueType  # 2
    """exact match search"""
    Fuzzy: GetSearchNotesRequest.SearchType.ValueType  # 3
    """typo tolerant search"""
    Context: GetSearchNotesRequest.SearchType.ValueType  # 4
    """semantic search using embeddings"""

    SEARCH_TYPE_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    search_type: Global___GetSearchNotesRequest.SearchType.ValueType
    """Search parameters"""
    query: _builtins.str
    limit: _builtins.int
    """Pagination"""
    offset: _builtins.int
    user_id: _builtins.str
    """authentication"""
    def __init__(
        self,
        *,
        search_type: Global___GetSearchNotesRequest.SearchType.ValueType = ...,
        query: _builtins.str = ...,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "offset", b"offset", "query", b"query", "search_type", b"search_type", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSearchNotesRequest: _TypeAlias = GetSearchNotesRequest  # noqa: Y015

@_typing.final
class NotesReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NOTES_FIELD_NUMBER: _builtins.int
    DIRECTORIES_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def notes(self) -> _containers.RepeatedCompositeFieldContainer[Global___MinimalNote]: ...
    @_builtins.property
    def directories(self) -> _containers.RepeatedCompositeFieldContainer[Global___MinimalDirectory]:
        """the directories which appear in the note results"""

    @_builtins.property
    def tags(self) -> _containers.RepeatedCompositeFieldContainer[Global___MinimalTag]:
        """the tags which appear in the note results"""

    def __init__(
        self,
        *,
        notes: _abc.Iterable[Global___MinimalNote] | None = ...,
        directories: _abc.Iterable[Global___MinimalDirectory] | None = ...,
        tags: _abc.Iterable[Global___MinimalTag] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["directories", b"directories", "notes", b"notes", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NotesReply: _TypeAlias = NotesReply  # noqa: Y015

@_typing.final
class MinimalNote(_message.Message):
    """Response: represents a minimal Note for search results"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    AUTHOR_ID_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    STRIPPED_CONTENT_FIELD_NUMBER: _builtins.int
    PERMISSIONS_FIELD_NUMBER: _builtins.int
    DIRECTORY_IDS_FIELD_NUMBER: _builtins.int
    TAG_IDS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Note ID (UUIDv7 string)"""
    title: _builtins.str
    author_id: _builtins.str
    stripped_content: _builtins.str
    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def permissions(self) -> _containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    @_builtins.property
    def directory_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def tag_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        title: _builtins.str = ...,
        author_id: _builtins.str = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
        stripped_content: _builtins.str = ...,
        permissions: _abc.Iterable[Global___PermissionRelationship] | None = ...,
        directory_ids: _abc.Iterable[_builtins.str] | None = ...,
        tag_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["author_id", b"author_id", "directory_ids", b"directory_ids", "id", b"id", "permissions", b"permissions", "stripped_content", b"stripped_content", "tag_ids", b"tag_ids", "title", b"title", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MinimalNote: _TypeAlias = MinimalNote  # noqa: Y015

@_typing.final
class MinimalDirectory(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    slug: _builtins.str
    display_name: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        slug: _builtins.str = ...,
        display_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["display_name", b"display_name", "id", b"id", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MinimalDirectory: _TypeAlias = MinimalDirectory  # noqa: Y015

@_typing.final
class MinimalTag(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    slug: _builtins.str
    display_name: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        slug: _builtins.str = ...,
        display_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["display_name", b"display_name", "id", b"id", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MinimalTag: _TypeAlias = MinimalTag  # noqa: Y015

@_typing.final
class Note(_message.Message):
    """Response: represents a Note"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    AUTHOR_ID_FIELD_NUMBER: _builtins.int
    PERMISSIONS_FIELD_NUMBER: _builtins.int
    DIRECTORY_IDS_FIELD_NUMBER: _builtins.int
    TAG_IDS_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    title: _builtins.str
    content: _builtins.str
    author_id: _builtins.str
    user_id: _builtins.str
    """used for permission checking"""
    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def permissions(self) -> _containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]:
        """repeated NoteEmbedding embeddings = 6;"""

    @_builtins.property
    def directory_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def tag_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        title: _builtins.str = ...,
        content: _builtins.str = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
        author_id: _builtins.str = ...,
        permissions: _abc.Iterable[Global___PermissionRelationship] | None = ...,
        directory_ids: _abc.Iterable[_builtins.str] | None = ...,
        tag_ids: _abc.Iterable[_builtins.str] | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["author_id", b"author_id", "content", b"content", "directory_ids", b"directory_ids", "id", b"id", "permissions", b"permissions", "tag_ids", b"tag_ids", "title", b"title", "updated_at", b"updated_at", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Note: _TypeAlias = Note  # noqa: Y015

@_typing.final
class NoteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class IdTokenMapEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NOTE_FIELD_NUMBER: _builtins.int
    ID_TOKEN_MAP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def note(self) -> Global___Note: ...
    @_builtins.property
    def id_token_map(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        note: Global___Note | None = ...,
        id_token_map: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["note", b"note"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id_token_map", b"id_token_map", "note", b"note"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NoteResponse: _TypeAlias = NoteResponse  # noqa: Y015

@_typing.final
class NoteEmbedding(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_FIELD_NUMBER: _builtins.int
    EMBEDDING_FIELD_NUMBER: _builtins.int
    model: _builtins.str
    @_builtins.property
    def embedding(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        model: _builtins.str = ...,
        embedding: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["embedding", b"embedding", "model", b"model"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NoteEmbedding: _TypeAlias = NoteEmbedding  # noqa: Y015

@_typing.final
class PostNoteRequest(_message.Message):
    """Request to add a note"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    AUTHOR_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    content: _builtins.str
    author_id: _builtins.str
    user_id: _builtins.str
    """the id of the user making the request - used for permission checking"""
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        content: _builtins.str | None = ...,
        author_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_content", b"_content", "content", b"content"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_content", b"_content", "author_id", b"author_id", "content", b"content", "title", b"title", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__content: _TypeAlias = _typing.Literal["content"]  # noqa: Y015
    _WhichOneofArgType__content: _TypeAlias = _typing.Literal["_content", b"_content"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__content) -> _WhichOneofReturnType__content | None: ...

Global___PostNoteRequest: _TypeAlias = PostNoteRequest  # noqa: Y015

@_typing.final
class DeleteNoteRequest(_message.Message):
    """Request to delete a note"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    user_id: _builtins.str
    """the id of the user making the request - used for permission checking"""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteNoteRequest: _TypeAlias = DeleteNoteRequest  # noqa: Y015

@_typing.final
class AlterNoteRequest(_message.Message):
    """Request to alter a note. Any omitted fields will be left unchanged, and any repeated fields will be replaced with the new values."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    AUTHOR_ID_FIELD_NUMBER: _builtins.int
    DIRECTORY_IDS_FIELD_NUMBER: _builtins.int
    TAG_IDS_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    title: _builtins.str
    content: _builtins.str
    author_id: _builtins.str
    user_id: _builtins.str
    """the user_id of the user making the request, used for permission checking"""
    @_builtins.property
    def directory_ids(self) -> Global___IdsOrUndefined: ...
    @_builtins.property
    def tag_ids(self) -> Global___IdsOrUndefined: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        title: _builtins.str | None = ...,
        content: _builtins.str | None = ...,
        author_id: _builtins.str | None = ...,
        directory_ids: Global___IdsOrUndefined | None = ...,
        tag_ids: Global___IdsOrUndefined | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_author_id", b"_author_id", "_content", b"_content", "_title", b"_title", "author_id", b"author_id", "content", b"content", "directory_ids", b"directory_ids", "directory_ids_change", b"directory_ids_change", "tag_ids", b"tag_ids", "tag_ids_change", b"tag_ids_change", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_author_id", b"_author_id", "_content", b"_content", "_title", b"_title", "author_id", b"author_id", "content", b"content", "directory_ids", b"directory_ids", "directory_ids_change", b"directory_ids_change", "id", b"id", "tag_ids", b"tag_ids", "tag_ids_change", b"tag_ids_change", "title", b"title", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__author_id: _TypeAlias = _typing.Literal["author_id"]  # noqa: Y015
    _WhichOneofArgType__author_id: _TypeAlias = _typing.Literal["_author_id", b"_author_id"]  # noqa: Y015
    _WhichOneofReturnType__content: _TypeAlias = _typing.Literal["content"]  # noqa: Y015
    _WhichOneofArgType__content: _TypeAlias = _typing.Literal["_content", b"_content"]  # noqa: Y015
    _WhichOneofReturnType__title: _TypeAlias = _typing.Literal["title"]  # noqa: Y015
    _WhichOneofArgType__title: _TypeAlias = _typing.Literal["_title", b"_title"]  # noqa: Y015
    _WhichOneofReturnType_directory_ids_change: _TypeAlias = _typing.Literal["directory_ids"]  # noqa: Y015
    _WhichOneofArgType_directory_ids_change: _TypeAlias = _typing.Literal["directory_ids_change", b"directory_ids_change"]  # noqa: Y015
    _WhichOneofReturnType_tag_ids_change: _TypeAlias = _typing.Literal["tag_ids"]  # noqa: Y015
    _WhichOneofArgType_tag_ids_change: _TypeAlias = _typing.Literal["tag_ids_change", b"tag_ids_change"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__author_id) -> _WhichOneofReturnType__author_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__content) -> _WhichOneofReturnType__content | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__title) -> _WhichOneofReturnType__title | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_directory_ids_change) -> _WhichOneofReturnType_directory_ids_change | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_tag_ids_change) -> _WhichOneofReturnType_tag_ids_change | None: ...

Global___AlterNoteRequest: _TypeAlias = AlterNoteRequest  # noqa: Y015

@_typing.final
class IdsOrUndefined(_message.Message):
    """repeated fields dont have a HasField. So we wrap them into a
    `oneof` to distinguish "not set" from "explicitly cleared".
    """

    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IdsOrUndefined: _TypeAlias = IdsOrUndefined  # noqa: Y015

@_typing.final
class Directory(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    IMAGE_URL_FIELD_NUMBER: _builtins.int
    PARENT_DIR_IDS_FIELD_NUMBER: _builtins.int
    RELATIONSHIPS_FIELD_NUMBER: _builtins.int
    CHILD_DIR_IDS_FIELD_NUMBER: _builtins.int
    CHILD_NOTE_IDS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    slug: _builtins.str
    display_name: _builtins.str
    description: _builtins.str
    image_url: _builtins.str
    @_builtins.property
    def parent_dir_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def relationships(self) -> _containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    @_builtins.property
    def child_dir_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def child_note_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        slug: _builtins.str = ...,
        display_name: _builtins.str = ...,
        description: _builtins.str = ...,
        image_url: _builtins.str = ...,
        parent_dir_ids: _abc.Iterable[_builtins.str] | None = ...,
        relationships: _abc.Iterable[Global___PermissionRelationship] | None = ...,
        child_dir_ids: _abc.Iterable[_builtins.str] | None = ...,
        child_note_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["child_dir_ids", b"child_dir_ids", "child_note_ids", b"child_note_ids", "description", b"description", "display_name", b"display_name", "id", b"id", "image_url", b"image_url", "parent_dir_ids", b"parent_dir_ids", "relationships", b"relationships", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Directory: _TypeAlias = Directory  # noqa: Y015

@_typing.final
class GetDirectoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    INCLUDE_PARENTS_FIELD_NUMBER: _builtins.int
    INCLUDE_CHILD_DIRS_FIELD_NUMBER: _builtins.int
    INCLUDE_CHILD_NOTES_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    user_id: _builtins.str
    include_parents: _builtins.bool
    include_child_dirs: _builtins.bool
    include_child_notes: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        include_parents: _builtins.bool = ...,
        include_child_dirs: _builtins.bool = ...,
        include_child_notes: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "include_child_dirs", b"include_child_dirs", "include_child_notes", b"include_child_notes", "include_parents", b"include_parents", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetDirectoryRequest: _TypeAlias = GetDirectoryRequest  # noqa: Y015

@_typing.final
class GetDirectoriesRequest(_message.Message):
    """list all directory contents of a given directory <parent_id>"""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    PARENT_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    INCLUDE_PARENTS_FIELD_NUMBER: _builtins.int
    INCLUDE_CHILD_DIRS_FIELD_NUMBER: _builtins.int
    INCLUDE_CHILD_NOTES_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    """the requesting user's id, used for permission checking"""
    parent_id: _builtins.str
    limit: _builtins.int
    offset: _builtins.int
    include_parents: _builtins.bool
    include_child_dirs: _builtins.bool
    include_child_notes: _builtins.bool
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        parent_id: _builtins.str | None = ...,
        limit: _builtins.int | None = ...,
        offset: _builtins.int | None = ...,
        include_parents: _builtins.bool = ...,
        include_child_dirs: _builtins.bool = ...,
        include_child_notes: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_limit", b"_limit", "_offset", b"_offset", "_parent_id", b"_parent_id", "limit", b"limit", "offset", b"offset", "parent_id", b"parent_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_limit", b"_limit", "_offset", b"_offset", "_parent_id", b"_parent_id", "include_child_dirs", b"include_child_dirs", "include_child_notes", b"include_child_notes", "include_parents", b"include_parents", "limit", b"limit", "offset", b"offset", "parent_id", b"parent_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__limit: _TypeAlias = _typing.Literal["limit"]  # noqa: Y015
    _WhichOneofArgType__limit: _TypeAlias = _typing.Literal["_limit", b"_limit"]  # noqa: Y015
    _WhichOneofReturnType__offset: _TypeAlias = _typing.Literal["offset"]  # noqa: Y015
    _WhichOneofArgType__offset: _TypeAlias = _typing.Literal["_offset", b"_offset"]  # noqa: Y015
    _WhichOneofReturnType__parent_id: _TypeAlias = _typing.Literal["parent_id"]  # noqa: Y015
    _WhichOneofArgType__parent_id: _TypeAlias = _typing.Literal["_parent_id", b"_parent_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__limit) -> _WhichOneofReturnType__limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__offset) -> _WhichOneofReturnType__offset | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_id) -> _WhichOneofReturnType__parent_id | None: ...

Global___GetDirectoriesRequest: _TypeAlias = GetDirectoriesRequest  # noqa: Y015

@_typing.final
class CreateDirectoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    IMAGE_URL_FIELD_NUMBER: _builtins.int
    PARENT_IDS_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    display_name: _builtins.str
    description: _builtins.str
    image_url: _builtins.str
    user_id: _builtins.str
    """the user_id of the user making the request, used for permission checking
    its also the author of the directory
    """
    @_builtins.property
    def parent_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        display_name: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        image_url: _builtins.str | None = ...,
        parent_ids: _abc.Iterable[_builtins.str] | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "description", b"description", "display_name", b"display_name", "image_url", b"image_url"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "description", b"description", "display_name", b"display_name", "image_url", b"image_url", "name", b"name", "parent_ids", b"parent_ids", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__display_name: _TypeAlias = _typing.Literal["display_name"]  # noqa: Y015
    _WhichOneofArgType__display_name: _TypeAlias = _typing.Literal["_display_name", b"_display_name"]  # noqa: Y015
    _WhichOneofReturnType__image_url: _TypeAlias = _typing.Literal["image_url"]  # noqa: Y015
    _WhichOneofArgType__image_url: _TypeAlias = _typing.Literal["_image_url", b"_image_url"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__display_name) -> _WhichOneofReturnType__display_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__image_url) -> _WhichOneofReturnType__image_url | None: ...

Global___CreateDirectoryRequest: _TypeAlias = CreateDirectoryRequest  # noqa: Y015

@_typing.final
class AlterDirectoryRequest(_message.Message):
    """any ommited fields will be left unchanged 
    and any repeated fields will be replaced with the new values.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    IMAGE_URL_FIELD_NUMBER: _builtins.int
    PARENT_IDS_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    display_name: _builtins.str
    description: _builtins.str
    image_url: _builtins.str
    user_id: _builtins.str
    @_builtins.property
    def parent_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str | None = ...,
        display_name: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        image_url: _builtins.str | None = ...,
        parent_ids: _abc.Iterable[_builtins.str] | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "_name", b"_name", "description", b"description", "display_name", b"display_name", "image_url", b"image_url", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "_name", b"_name", "description", b"description", "display_name", b"display_name", "id", b"id", "image_url", b"image_url", "name", b"name", "parent_ids", b"parent_ids", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__display_name: _TypeAlias = _typing.Literal["display_name"]  # noqa: Y015
    _WhichOneofArgType__display_name: _TypeAlias = _typing.Literal["_display_name", b"_display_name"]  # noqa: Y015
    _WhichOneofReturnType__image_url: _TypeAlias = _typing.Literal["image_url"]  # noqa: Y015
    _WhichOneofArgType__image_url: _TypeAlias = _typing.Literal["_image_url", b"_image_url"]  # noqa: Y015
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__display_name) -> _WhichOneofReturnType__display_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__image_url) -> _WhichOneofReturnType__image_url | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___AlterDirectoryRequest: _TypeAlias = AlterDirectoryRequest  # noqa: Y015

@_typing.final
class DeleteDirectoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteDirectoryRequest: _TypeAlias = DeleteDirectoryRequest  # noqa: Y015

@_typing.final
class GetNotesOfDirectoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DIRECTORY_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    directory_id: _builtins.str
    limit: _builtins.int
    offset: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        directory_id: _builtins.str = ...,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["directory_id", b"directory_id", "limit", b"limit", "offset", b"offset", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetNotesOfDirectoryRequest: _TypeAlias = GetNotesOfDirectoryRequest  # noqa: Y015

@_typing.final
class PermissionSubject(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: _builtins.str
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id", "object_type", b"object_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PermissionSubject: _TypeAlias = PermissionSubject  # noqa: Y015

@_typing.final
class PermissionResource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: _builtins.str
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id", "object_type", b"object_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PermissionResource: _TypeAlias = PermissionResource  # noqa: Y015

@_typing.final
class PermissionRelationship(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELATION_FIELD_NUMBER: _builtins.int
    SUBJECT_FIELD_NUMBER: _builtins.int
    RESOURCE_FIELD_NUMBER: _builtins.int
    relation: _builtins.str
    @_builtins.property
    def subject(self) -> Global___PermissionSubject: ...
    @_builtins.property
    def resource(self) -> Global___PermissionResource: ...
    def __init__(
        self,
        *,
        relation: _builtins.str = ...,
        subject: Global___PermissionSubject | None = ...,
        resource: Global___PermissionResource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resource", b"resource", "subject", b"subject"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["relation", b"relation", "resource", b"resource", "subject", b"subject"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PermissionRelationship: _TypeAlias = PermissionRelationship  # noqa: Y015

@_typing.final
class GetPermissionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: _builtins.str
    user_id: _builtins.str
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id", "object_type", b"object_type", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPermissionsRequest: _TypeAlias = GetPermissionsRequest  # noqa: Y015

@_typing.final
class CreatePermissionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    RELATIONSHIP_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: _builtins.str
    user_id: _builtins.str
    @_builtins.property
    def relationship(self) -> Global___PermissionRelationship: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: _builtins.str = ...,
        relationship: Global___PermissionRelationship | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["relationship", b"relationship"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationship", b"relationship", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePermissionRequest: _TypeAlias = CreatePermissionRequest  # noqa: Y015

@_typing.final
class DeletePermissionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    RELATIONSHIP_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: _builtins.str
    user_id: _builtins.str
    @_builtins.property
    def relationship(self) -> Global___PermissionRelationship: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: _builtins.str = ...,
        relationship: Global___PermissionRelationship | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["relationship", b"relationship"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationship", b"relationship", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeletePermissionRequest: _TypeAlias = DeletePermissionRequest  # noqa: Y015

@_typing.final
class ReplacePermissionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    RELATIONSHIPS_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: _builtins.str
    user_id: _builtins.str
    @_builtins.property
    def relationships(self) -> _containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: _builtins.str = ...,
        relationships: _abc.Iterable[Global___PermissionRelationship] | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationships", b"relationships", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReplacePermissionsRequest: _TypeAlias = ReplacePermissionsRequest  # noqa: Y015

@_typing.final
class PermissionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    RELATIONSHIPS_FIELD_NUMBER: _builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: _builtins.str
    @_builtins.property
    def relationships(self) -> _containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: _builtins.str = ...,
        relationships: _abc.Iterable[Global___PermissionRelationship] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationships", b"relationships"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PermissionsResponse: _TypeAlias = PermissionsResponse  # noqa: Y015

@_typing.final
class NoteVersionSummary(_message.Message):
    """Versioning requests and responses"""

    DESCRIPTOR: _descriptor.Descriptor

    VERSION_ID_FIELD_NUMBER: _builtins.int
    NOTE_ID_FIELD_NUMBER: _builtins.int
    VERSION_INDEX_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    AUTHOR_ID_FIELD_NUMBER: _builtins.int
    IS_SNAPSHOT_FIELD_NUMBER: _builtins.int
    SNAPSHOT_ID_FIELD_NUMBER: _builtins.int
    version_id: _builtins.str
    note_id: _builtins.str
    version_index: _builtins.int
    author_id: _builtins.str
    is_snapshot: _builtins.bool
    snapshot_id: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        version_id: _builtins.str = ...,
        note_id: _builtins.str = ...,
        version_index: _builtins.int = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        author_id: _builtins.str = ...,
        is_snapshot: _builtins.bool = ...,
        snapshot_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["author_id", b"author_id", "created_at", b"created_at", "is_snapshot", b"is_snapshot", "note_id", b"note_id", "snapshot_id", b"snapshot_id", "version_id", b"version_id", "version_index", b"version_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NoteVersionSummary: _TypeAlias = NoteVersionSummary  # noqa: Y015

@_typing.final
class GetNoteVersionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NOTE_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    note_id: _builtins.str
    limit: _builtins.int
    offset: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        note_id: _builtins.str = ...,
        limit: _builtins.int | None = ...,
        offset: _builtins.int | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_limit", b"_limit", "_offset", b"_offset", "limit", b"limit", "offset", b"offset"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_limit", b"_limit", "_offset", b"_offset", "limit", b"limit", "note_id", b"note_id", "offset", b"offset", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__limit: _TypeAlias = _typing.Literal["limit"]  # noqa: Y015
    _WhichOneofArgType__limit: _TypeAlias = _typing.Literal["_limit", b"_limit"]  # noqa: Y015
    _WhichOneofReturnType__offset: _TypeAlias = _typing.Literal["offset"]  # noqa: Y015
    _WhichOneofArgType__offset: _TypeAlias = _typing.Literal["_offset", b"_offset"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__limit) -> _WhichOneofReturnType__limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__offset) -> _WhichOneofReturnType__offset | None: ...

Global___GetNoteVersionsRequest: _TypeAlias = GetNoteVersionsRequest  # noqa: Y015

@_typing.final
class GetDirectoryActivityRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DIRECTORY_ID_FIELD_NUMBER: _builtins.int
    MAX_DEPTH_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    directory_id: _builtins.str
    max_depth: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        directory_id: _builtins.str | None = ...,
        max_depth: _builtins.int | None = ...,
        limit: _builtins.int | None = ...,
        offset: _builtins.int | None = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_directory_id", b"_directory_id", "_limit", b"_limit", "_max_depth", b"_max_depth", "_offset", b"_offset", "directory_id", b"directory_id", "limit", b"limit", "max_depth", b"max_depth", "offset", b"offset"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_directory_id", b"_directory_id", "_limit", b"_limit", "_max_depth", b"_max_depth", "_offset", b"_offset", "directory_id", b"directory_id", "limit", b"limit", "max_depth", b"max_depth", "offset", b"offset", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__directory_id: _TypeAlias = _typing.Literal["directory_id"]  # noqa: Y015
    _WhichOneofArgType__directory_id: _TypeAlias = _typing.Literal["_directory_id", b"_directory_id"]  # noqa: Y015
    _WhichOneofReturnType__limit: _TypeAlias = _typing.Literal["limit"]  # noqa: Y015
    _WhichOneofArgType__limit: _TypeAlias = _typing.Literal["_limit", b"_limit"]  # noqa: Y015
    _WhichOneofReturnType__max_depth: _TypeAlias = _typing.Literal["max_depth"]  # noqa: Y015
    _WhichOneofArgType__max_depth: _TypeAlias = _typing.Literal["_max_depth", b"_max_depth"]  # noqa: Y015
    _WhichOneofReturnType__offset: _TypeAlias = _typing.Literal["offset"]  # noqa: Y015
    _WhichOneofArgType__offset: _TypeAlias = _typing.Literal["_offset", b"_offset"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__directory_id) -> _WhichOneofReturnType__directory_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__limit) -> _WhichOneofReturnType__limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_depth) -> _WhichOneofReturnType__max_depth | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__offset) -> _WhichOneofReturnType__offset | None: ...

Global___GetDirectoryActivityRequest: _TypeAlias = GetDirectoryActivityRequest  # noqa: Y015

@_typing.final
class NoteVersionContent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NOTE_ID_FIELD_NUMBER: _builtins.int
    VERSION_INDEX_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    AUTHOR_ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    note_id: _builtins.str
    version_index: _builtins.int
    author_id: _builtins.str
    title: _builtins.str
    content: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        note_id: _builtins.str = ...,
        version_index: _builtins.int = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        author_id: _builtins.str = ...,
        title: _builtins.str = ...,
        content: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["author_id", b"author_id", "content", b"content", "created_at", b"created_at", "note_id", b"note_id", "title", b"title", "version_index", b"version_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NoteVersionContent: _TypeAlias = NoteVersionContent  # noqa: Y015

@_typing.final
class GetNoteVersionContentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NOTE_ID_FIELD_NUMBER: _builtins.int
    VERSION_INDEX_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    note_id: _builtins.str
    version_index: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        note_id: _builtins.str = ...,
        version_index: _builtins.int = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["note_id", b"note_id", "user_id", b"user_id", "version_index", b"version_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetNoteVersionContentRequest: _TypeAlias = GetNoteVersionContentRequest  # noqa: Y015

@_typing.final
class RestoreNoteVersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NOTE_ID_FIELD_NUMBER: _builtins.int
    VERSION_INDEX_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    note_id: _builtins.str
    version_index: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        note_id: _builtins.str = ...,
        version_index: _builtins.int = ...,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["note_id", b"note_id", "user_id", b"user_id", "version_index", b"version_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RestoreNoteVersionRequest: _TypeAlias = RestoreNoteVersionRequest  # noqa: Y015
