"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PermissionObjectType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PermissionObjectTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PermissionObjectType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PERMISSION_OBJECT_TYPE_UNSPECIFIED: _PermissionObjectType.ValueType  # 0
    PERMISSION_OBJECT_TYPE_NOTE: _PermissionObjectType.ValueType  # 1
    PERMISSION_OBJECT_TYPE_DIRECTORY: _PermissionObjectType.ValueType  # 2
    PERMISSION_OBJECT_TYPE_USER: _PermissionObjectType.ValueType  # 3

class PermissionObjectType(_PermissionObjectType, metaclass=_PermissionObjectTypeEnumTypeWrapper): ...

PERMISSION_OBJECT_TYPE_UNSPECIFIED: PermissionObjectType.ValueType  # 0
PERMISSION_OBJECT_TYPE_NOTE: PermissionObjectType.ValueType  # 1
PERMISSION_OBJECT_TYPE_DIRECTORY: PermissionObjectType.ValueType  # 2
PERMISSION_OBJECT_TYPE_USER: PermissionObjectType.ValueType  # 3
Global___PermissionObjectType: typing_extensions.TypeAlias = PermissionObjectType

@typing.final
class GetNoteRequest(google.protobuf.message.Message):
    """Request for getting a note by id"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    user_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "user_id", b"user_id"]) -> None: ...

Global___GetNoteRequest: typing_extensions.TypeAlias = GetNoteRequest

@typing.final
class GetSearchNotesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SearchType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SearchTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GetSearchNotesRequest._SearchType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Undefined: GetSearchNotesRequest._SearchType.ValueType  # 0
        """default"""
        NoSearch: GetSearchNotesRequest._SearchType.ValueType  # 1
        """just"""
        FullTextTitle: GetSearchNotesRequest._SearchType.ValueType  # 2
        """exact match search"""
        Fuzzy: GetSearchNotesRequest._SearchType.ValueType  # 3
        """typo tolerant search"""
        Context: GetSearchNotesRequest._SearchType.ValueType  # 4
        """semantic search using embeddings"""

    class SearchType(_SearchType, metaclass=_SearchTypeEnumTypeWrapper): ...
    Undefined: GetSearchNotesRequest.SearchType.ValueType  # 0
    """default"""
    NoSearch: GetSearchNotesRequest.SearchType.ValueType  # 1
    """just"""
    FullTextTitle: GetSearchNotesRequest.SearchType.ValueType  # 2
    """exact match search"""
    Fuzzy: GetSearchNotesRequest.SearchType.ValueType  # 3
    """typo tolerant search"""
    Context: GetSearchNotesRequest.SearchType.ValueType  # 4
    """semantic search using embeddings"""

    SEARCH_TYPE_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    search_type: Global___GetSearchNotesRequest.SearchType.ValueType
    """Search parameters"""
    query: builtins.str
    limit: builtins.int
    """Pagination"""
    offset: builtins.int
    user_id: builtins.str
    """authentication"""
    def __init__(
        self,
        *,
        search_type: Global___GetSearchNotesRequest.SearchType.ValueType = ...,
        query: builtins.str = ...,
        limit: builtins.int = ...,
        offset: builtins.int = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "offset", b"offset", "query", b"query", "search_type", b"search_type", "user_id", b"user_id"]) -> None: ...

Global___GetSearchNotesRequest: typing_extensions.TypeAlias = GetSearchNotesRequest

@typing.final
class MinimalNote(google.protobuf.message.Message):
    """Response: represents a minimal Note for search results"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    STRIPPED_CONTENT_FIELD_NUMBER: builtins.int
    PERMISSIONS_FIELD_NUMBER: builtins.int
    id: builtins.str
    """Note ID (UUIDv4 string)"""
    title: builtins.str
    author_id: builtins.str
    stripped_content: builtins.str
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def permissions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        title: builtins.str = ...,
        author_id: builtins.str = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        stripped_content: builtins.str = ...,
        permissions: collections.abc.Iterable[Global___PermissionRelationship] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["author_id", b"author_id", "id", b"id", "permissions", b"permissions", "stripped_content", b"stripped_content", "title", b"title", "updated_at", b"updated_at"]) -> None: ...

Global___MinimalNote: typing_extensions.TypeAlias = MinimalNote

@typing.final
class Note(google.protobuf.message.Message):
    """Response: represents a Note"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    PERMISSIONS_FIELD_NUMBER: builtins.int
    id: builtins.str
    title: builtins.str
    content: builtins.str
    author_id: builtins.str
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def permissions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]:
        """repeated NoteEmbedding embeddings = 6;"""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        title: builtins.str = ...,
        content: builtins.str = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        author_id: builtins.str = ...,
        permissions: collections.abc.Iterable[Global___PermissionRelationship] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["author_id", b"author_id", "content", b"content", "id", b"id", "permissions", b"permissions", "title", b"title", "updated_at", b"updated_at"]) -> None: ...

Global___Note: typing_extensions.TypeAlias = Note

@typing.final
class NoteEmbedding(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEL_FIELD_NUMBER: builtins.int
    EMBEDDING_FIELD_NUMBER: builtins.int
    model: builtins.str
    @property
    def embedding(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        model: builtins.str = ...,
        embedding: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["embedding", b"embedding", "model", b"model"]) -> None: ...

Global___NoteEmbedding: typing_extensions.TypeAlias = NoteEmbedding

@typing.final
class PostNoteRequest(google.protobuf.message.Message):
    """Request to add a note"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    title: builtins.str
    content: builtins.str
    author_id: builtins.str
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        content: builtins.str | None = ...,
        author_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_content", b"_content", "content", b"content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_content", b"_content", "author_id", b"author_id", "content", b"content", "title", b"title"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_content", b"_content"]) -> typing.Literal["content"] | None: ...

Global___PostNoteRequest: typing_extensions.TypeAlias = PostNoteRequest

@typing.final
class DeleteNoteRequest(google.protobuf.message.Message):
    """Request to delete a note"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    author_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        author_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["author_id", b"author_id", "id", b"id"]) -> None: ...

Global___DeleteNoteRequest: typing_extensions.TypeAlias = DeleteNoteRequest

@typing.final
class AlterNoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    title: builtins.str
    content: builtins.str
    author_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        title: builtins.str | None = ...,
        content: builtins.str | None = ...,
        author_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_author_id", b"_author_id", "_content", b"_content", "_title", b"_title", "author_id", b"author_id", "content", b"content", "title", b"title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_author_id", b"_author_id", "_content", b"_content", "_title", b"_title", "author_id", b"author_id", "content", b"content", "id", b"id", "title", b"title"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_author_id", b"_author_id"]) -> typing.Literal["author_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_content", b"_content"]) -> typing.Literal["content"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

Global___AlterNoteRequest: typing_extensions.TypeAlias = AlterNoteRequest

@typing.final
class Directory(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    IMAGE_URL_FIELD_NUMBER: builtins.int
    PARENT_ID_FIELD_NUMBER: builtins.int
    RELATIONSHIPS_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    display_name: builtins.str
    description: builtins.str
    image_url: builtins.str
    parent_id: builtins.str
    @property
    def relationships(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        display_name: builtins.str = ...,
        description: builtins.str = ...,
        image_url: builtins.str = ...,
        parent_id: builtins.str | None = ...,
        relationships: collections.abc.Iterable[Global___PermissionRelationship] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_parent_id", b"_parent_id", "parent_id", b"parent_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_parent_id", b"_parent_id", "description", b"description", "display_name", b"display_name", "id", b"id", "image_url", b"image_url", "name", b"name", "parent_id", b"parent_id", "relationships", b"relationships"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_parent_id", b"_parent_id"]) -> typing.Literal["parent_id"] | None: ...

Global___Directory: typing_extensions.TypeAlias = Directory

@typing.final
class GetDirectoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    user_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "user_id", b"user_id"]) -> None: ...

Global___GetDirectoryRequest: typing_extensions.TypeAlias = GetDirectoryRequest

@typing.final
class CreateDirectoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    IMAGE_URL_FIELD_NUMBER: builtins.int
    PARENT_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    name: builtins.str
    display_name: builtins.str
    description: builtins.str
    image_url: builtins.str
    parent_id: builtins.str
    user_id: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        display_name: builtins.str | None = ...,
        description: builtins.str | None = ...,
        image_url: builtins.str | None = ...,
        parent_id: builtins.str | None = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "_parent_id", b"_parent_id", "description", b"description", "display_name", b"display_name", "image_url", b"image_url", "parent_id", b"parent_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "_parent_id", b"_parent_id", "description", b"description", "display_name", b"display_name", "image_url", b"image_url", "name", b"name", "parent_id", b"parent_id", "user_id", b"user_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_display_name", b"_display_name"]) -> typing.Literal["display_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_image_url", b"_image_url"]) -> typing.Literal["image_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_parent_id", b"_parent_id"]) -> typing.Literal["parent_id"] | None: ...

Global___CreateDirectoryRequest: typing_extensions.TypeAlias = CreateDirectoryRequest

@typing.final
class AlterDirectoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    IMAGE_URL_FIELD_NUMBER: builtins.int
    PARENT_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    display_name: builtins.str
    description: builtins.str
    image_url: builtins.str
    parent_id: builtins.str
    user_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str | None = ...,
        display_name: builtins.str | None = ...,
        description: builtins.str | None = ...,
        image_url: builtins.str | None = ...,
        parent_id: builtins.str | None = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "_name", b"_name", "_parent_id", b"_parent_id", "description", b"description", "display_name", b"display_name", "image_url", b"image_url", "name", b"name", "parent_id", b"parent_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_display_name", b"_display_name", "_image_url", b"_image_url", "_name", b"_name", "_parent_id", b"_parent_id", "description", b"description", "display_name", b"display_name", "id", b"id", "image_url", b"image_url", "name", b"name", "parent_id", b"parent_id", "user_id", b"user_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_display_name", b"_display_name"]) -> typing.Literal["display_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_image_url", b"_image_url"]) -> typing.Literal["image_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_parent_id", b"_parent_id"]) -> typing.Literal["parent_id"] | None: ...

Global___AlterDirectoryRequest: typing_extensions.TypeAlias = AlterDirectoryRequest

@typing.final
class DeleteDirectoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    user_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "user_id", b"user_id"]) -> None: ...

Global___DeleteDirectoryRequest: typing_extensions.TypeAlias = DeleteDirectoryRequest

@typing.final
class PermissionSubject(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: builtins.str
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_id", b"object_id", "object_type", b"object_type"]) -> None: ...

Global___PermissionSubject: typing_extensions.TypeAlias = PermissionSubject

@typing.final
class PermissionResource(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: builtins.str
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_id", b"object_id", "object_type", b"object_type"]) -> None: ...

Global___PermissionResource: typing_extensions.TypeAlias = PermissionResource

@typing.final
class PermissionRelationship(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RELATION_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    RESOURCE_FIELD_NUMBER: builtins.int
    relation: builtins.str
    @property
    def subject(self) -> Global___PermissionSubject: ...
    @property
    def resource(self) -> Global___PermissionResource: ...
    def __init__(
        self,
        *,
        relation: builtins.str = ...,
        subject: Global___PermissionSubject | None = ...,
        resource: Global___PermissionResource | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resource", b"resource", "subject", b"subject"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["relation", b"relation", "resource", b"resource", "subject", b"subject"]) -> None: ...

Global___PermissionRelationship: typing_extensions.TypeAlias = PermissionRelationship

@typing.final
class GetPermissionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: builtins.str
    user_id: builtins.str
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_id", b"object_id", "object_type", b"object_type", "user_id", b"user_id"]) -> None: ...

Global___GetPermissionsRequest: typing_extensions.TypeAlias = GetPermissionsRequest

@typing.final
class CreatePermissionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    RELATIONSHIP_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: builtins.str
    user_id: builtins.str
    @property
    def relationship(self) -> Global___PermissionRelationship: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: builtins.str = ...,
        relationship: Global___PermissionRelationship | None = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["relationship", b"relationship"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationship", b"relationship", "user_id", b"user_id"]) -> None: ...

Global___CreatePermissionRequest: typing_extensions.TypeAlias = CreatePermissionRequest

@typing.final
class DeletePermissionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    RELATIONSHIP_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: builtins.str
    user_id: builtins.str
    @property
    def relationship(self) -> Global___PermissionRelationship: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: builtins.str = ...,
        relationship: Global___PermissionRelationship | None = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["relationship", b"relationship"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationship", b"relationship", "user_id", b"user_id"]) -> None: ...

Global___DeletePermissionRequest: typing_extensions.TypeAlias = DeletePermissionRequest

@typing.final
class ReplacePermissionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    RELATIONSHIPS_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: builtins.str
    user_id: builtins.str
    @property
    def relationships(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: builtins.str = ...,
        relationships: collections.abc.Iterable[Global___PermissionRelationship] | None = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationships", b"relationships", "user_id", b"user_id"]) -> None: ...

Global___ReplacePermissionsRequest: typing_extensions.TypeAlias = ReplacePermissionsRequest

@typing.final
class PermissionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_ID_FIELD_NUMBER: builtins.int
    RELATIONSHIPS_FIELD_NUMBER: builtins.int
    object_type: Global___PermissionObjectType.ValueType
    object_id: builtins.str
    @property
    def relationships(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PermissionRelationship]: ...
    def __init__(
        self,
        *,
        object_type: Global___PermissionObjectType.ValueType = ...,
        object_id: builtins.str = ...,
        relationships: collections.abc.Iterable[Global___PermissionRelationship] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["object_id", b"object_id", "object_type", b"object_type", "relationships", b"relationships"]) -> None: ...

Global___PermissionsResponse: typing_extensions.TypeAlias = PermissionsResponse
