# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc_mod.proto import role_pb2 as role__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in role_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRole = channel.unary_unary(
                '/proto.RoleService/CreateRole',
                request_serializer=role__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=role__pb2.Role.FromString,
                _registered_method=True)
        self.UpdateRole = channel.unary_unary(
                '/proto.RoleService/UpdateRole',
                request_serializer=role__pb2.UpdateRoleRequest.SerializeToString,
                response_deserializer=role__pb2.Role.FromString,
                _registered_method=True)
        self.DeleteRole = channel.unary_unary(
                '/proto.RoleService/DeleteRole',
                request_serializer=role__pb2.DeleteRoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRole = channel.unary_unary(
                '/proto.RoleService/GetRole',
                request_serializer=role__pb2.GetRoleRequest.SerializeToString,
                response_deserializer=role__pb2.Role.FromString,
                _registered_method=True)
        self.GetRoles = channel.unary_stream(
                '/proto.RoleService/GetRoles',
                request_serializer=role__pb2.GetRolesRequest.SerializeToString,
                response_deserializer=role__pb2.Role.FromString,
                _registered_method=True)
        self.AddUserToRole = channel.unary_unary(
                '/proto.RoleService/AddUserToRole',
                request_serializer=role__pb2.AddUserToRoleRequest.SerializeToString,
                response_deserializer=role__pb2.UserRoleMembership.FromString,
                _registered_method=True)
        self.RemoveUserFromRole = channel.unary_unary(
                '/proto.RoleService/RemoveUserFromRole',
                request_serializer=role__pb2.RemoveUserFromRoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRolesForUser = channel.unary_stream(
                '/proto.RoleService/GetRolesForUser',
                request_serializer=role__pb2.GetRolesForUserRequest.SerializeToString,
                response_deserializer=role__pb2.Role.FromString,
                _registered_method=True)
        self.GetUsersForRole = channel.unary_stream(
                '/proto.RoleService/GetUsersForRole',
                request_serializer=role__pb2.GetUsersForRoleRequest.SerializeToString,
                response_deserializer=role__pb2.UserRoleMembership.FromString,
                _registered_method=True)


class RoleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRolesForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersForRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=role__pb2.CreateRoleRequest.FromString,
                    response_serializer=role__pb2.Role.SerializeToString,
            ),
            'UpdateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRole,
                    request_deserializer=role__pb2.UpdateRoleRequest.FromString,
                    response_serializer=role__pb2.Role.SerializeToString,
            ),
            'DeleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRole,
                    request_deserializer=role__pb2.DeleteRoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRole,
                    request_deserializer=role__pb2.GetRoleRequest.FromString,
                    response_serializer=role__pb2.Role.SerializeToString,
            ),
            'GetRoles': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRoles,
                    request_deserializer=role__pb2.GetRolesRequest.FromString,
                    response_serializer=role__pb2.Role.SerializeToString,
            ),
            'AddUserToRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToRole,
                    request_deserializer=role__pb2.AddUserToRoleRequest.FromString,
                    response_serializer=role__pb2.UserRoleMembership.SerializeToString,
            ),
            'RemoveUserFromRole': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromRole,
                    request_deserializer=role__pb2.RemoveUserFromRoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetRolesForUser': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRolesForUser,
                    request_deserializer=role__pb2.GetRolesForUserRequest.FromString,
                    response_serializer=role__pb2.Role.SerializeToString,
            ),
            'GetUsersForRole': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUsersForRole,
                    request_deserializer=role__pb2.GetUsersForRoleRequest.FromString,
                    response_serializer=role__pb2.UserRoleMembership.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.RoleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.RoleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RoleService/CreateRole',
            role__pb2.CreateRoleRequest.SerializeToString,
            role__pb2.Role.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RoleService/UpdateRole',
            role__pb2.UpdateRoleRequest.SerializeToString,
            role__pb2.Role.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RoleService/DeleteRole',
            role__pb2.DeleteRoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RoleService/GetRole',
            role__pb2.GetRoleRequest.SerializeToString,
            role__pb2.Role.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.RoleService/GetRoles',
            role__pb2.GetRolesRequest.SerializeToString,
            role__pb2.Role.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUserToRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RoleService/AddUserToRole',
            role__pb2.AddUserToRoleRequest.SerializeToString,
            role__pb2.UserRoleMembership.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUserFromRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RoleService/RemoveUserFromRole',
            role__pb2.RemoveUserFromRoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRolesForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.RoleService/GetRolesForUser',
            role__pb2.GetRolesForUserRequest.SerializeToString,
            role__pb2.Role.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersForRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.RoleService/GetUsersForRole',
            role__pb2.GetUsersForRoleRequest.SerializeToString,
            role__pb2.UserRoleMembership.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
