"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Role(_message.Message):
    """A role that bundles a set of users for permission grants.

    Metadata (name, description) lives in Postgres.  Membership edges
    (`user#member_of@role`) live in SpiceDB.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    description: _builtins.str
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "description", b"description", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Role: _TypeAlias = Role  # noqa: Y015

@_typing.final
class UserRoleMembership(_message.Message):
    """A single `user#member_of@role` edge."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ROLE_ID_FIELD_NUMBER: _builtins.int
    GRANTED_AT_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    role_id: _builtins.str
    @_builtins.property
    def granted_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        role_id: _builtins.str = ...,
        granted_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["granted_at", b"granted_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["granted_at", b"granted_at", "role_id", b"role_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UserRoleMembership: _TypeAlias = UserRoleMembership  # noqa: Y015

@_typing.final
class RoleFilter(_message.Message):
    """Filter for searching roles.

    `member_id` matches roles whose SpiceDB `user#member_of@role`
    relation includes the given user id.  `name` matches by exact
    role name.  Both fields are optional; unset means "don't filter
    on that field".
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    MEMBER_ID_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    member_id: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str | None = ...,
        member_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_member_id", b"_member_id", "_name", b"_name", "member_id", b"member_id", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_member_id", b"_member_id", "_name", b"_name", "member_id", b"member_id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__member_id: _TypeAlias = _typing.Literal["member_id"]  # noqa: Y015
    _WhichOneofArgType__member_id: _TypeAlias = _typing.Literal["_member_id", b"_member_id"]  # noqa: Y015
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__member_id) -> _WhichOneofReturnType__member_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___RoleFilter: _TypeAlias = RoleFilter  # noqa: Y015

@_typing.final
class CreateRoleRequest(_message.Message):
    """Create a new role.  The actor's user_id is used for permission
    checks (currently: must hold `manage` on the bootstrap role).
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    name: _builtins.str
    description: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "name", b"name", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateRoleRequest: _TypeAlias = CreateRoleRequest  # noqa: Y015

@_typing.final
class UpdateRoleRequest(_message.Message):
    """Update a role's metadata (name and/or description).  Membership
    is managed through `AddUserToRole` / `RemoveUserFromRole`.  The
    actor's user_id is used for permission checks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    id: _builtins.str
    name: _builtins.str
    description: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        id: _builtins.str = ...,
        name: _builtins.str | None = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "description", b"description", "id", b"id", "name", b"name", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___UpdateRoleRequest: _TypeAlias = UpdateRoleRequest  # noqa: Y015

@_typing.final
class DeleteRoleRequest(_message.Message):
    """Delete a role.  Membership edges become dangling references in
    SpiceDB (they silently evaluate to nothing); cleanup of those is
    the caller's responsibility.  The actor's user_id is used for
    permission checks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteRoleRequest: _TypeAlias = DeleteRoleRequest  # noqa: Y015

@_typing.final
class GetRoleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRoleRequest: _TypeAlias = GetRoleRequest  # noqa: Y015

@_typing.final
class GetRolesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    @_builtins.property
    def filter(self) -> Global___RoleFilter: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        filter: Global___RoleFilter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRolesRequest: _TypeAlias = GetRolesRequest  # noqa: Y015

@_typing.final
class AddUserToRoleRequest(_message.Message):
    """Add a user to a role's membership.  Gated by `manage` permission
    on the role.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ROLE_ID_FIELD_NUMBER: _builtins.int
    SUBJECT_USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    role_id: _builtins.str
    subject_user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        role_id: _builtins.str = ...,
        subject_user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["role_id", b"role_id", "subject_user_id", b"subject_user_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddUserToRoleRequest: _TypeAlias = AddUserToRoleRequest  # noqa: Y015

@_typing.final
class RemoveUserFromRoleRequest(_message.Message):
    """Remove a user from a role's membership.  Gated by `manage`
    permission on the role.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ROLE_ID_FIELD_NUMBER: _builtins.int
    SUBJECT_USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    role_id: _builtins.str
    subject_user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        role_id: _builtins.str = ...,
        subject_user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["role_id", b"role_id", "subject_user_id", b"subject_user_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveUserFromRoleRequest: _TypeAlias = RemoveUserFromRoleRequest  # noqa: Y015

@_typing.final
class GetRolesForUserRequest(_message.Message):
    """List every role the given user is a member of."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    SUBJECT_USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    subject_user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        subject_user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["subject_user_id", b"subject_user_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRolesForUserRequest: _TypeAlias = GetRolesForUserRequest  # noqa: Y015

@_typing.final
class GetUsersForRoleRequest(_message.Message):
    """List every user that is a member of the given role."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ROLE_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    role_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        role_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["role_id", b"role_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUsersForRoleRequest: _TypeAlias = GetUsersForRoleRequest  # noqa: Y015
