# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_mod.proto import rule_pb2 as src_dot_grpc__mod_dot_proto_dot_rule__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc_mod/proto/rule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuleServiceStub:
    """===== Service ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRule = channel.unary_unary(
                '/proto.RuleService/CreateRule',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.CreateRuleRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.CreateRuleResponse.FromString,
                _registered_method=True)
        self.GetRule = channel.unary_unary(
                '/proto.RuleService/GetRule',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRuleRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRuleResponse.FromString,
                _registered_method=True)
        self.GetRules = channel.unary_unary(
                '/proto.RuleService/GetRules',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRulesRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRulesResponse.FromString,
                _registered_method=True)
        self.UpdateRule = channel.unary_unary(
                '/proto.RuleService/UpdateRule',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.UpdateRuleRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.UpdateRuleResponse.FromString,
                _registered_method=True)
        self.DeleteRule = channel.unary_unary(
                '/proto.RuleService/DeleteRule',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.DeleteRuleRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.DeleteRuleResponse.FromString,
                _registered_method=True)


class RuleServiceServicer:
    """===== Service ============================================================

    """

    def CreateRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRule,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.CreateRuleRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.CreateRuleResponse.SerializeToString,
            ),
            'GetRule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRule,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRuleRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRuleResponse.SerializeToString,
            ),
            'GetRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRules,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRulesRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRulesResponse.SerializeToString,
            ),
            'UpdateRule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRule,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.UpdateRuleRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.UpdateRuleResponse.SerializeToString,
            ),
            'DeleteRule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRule,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.DeleteRuleRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_rule__pb2.DeleteRuleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.RuleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.RuleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuleService:
    """===== Service ============================================================

    """

    @staticmethod
    def CreateRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RuleService/CreateRule',
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.CreateRuleRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.CreateRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RuleService/GetRule',
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRuleRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RuleService/GetRules',
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRulesRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.GetRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RuleService/UpdateRule',
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.UpdateRuleRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.UpdateRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.RuleService/DeleteRule',
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.DeleteRuleRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_rule__pb2.DeleteRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
