"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import empty_pb2 as _empty_pb2
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Rule(_message.Message):
    """A rule is a stored if x then do y event. attached_entity describes
    an entity, where this rule is attached to. e.g. if event type
    is note_created and attached_entity is a directory, then the rule
    will only fire if the note is created in that directory.
    action type, describes the then action, e.g. add note to a directory etc

    The ``condition`` and ``action_context`` fields are carried as
    ``google.protobuf.Struct`` so the shape can evolve without breaking
    the gRPC contract.  Valid ``condition.type`` values:

      - "always_true"
      - "note_content_contains"   (with ``substring``)
      - "note_title_contains"     (with ``substring``)

    Valid ``action_type`` values:

      - "add_to_directory"        (with ``directory_id``)
      - "add_tag"                 (with ``tag_id``)
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_ID_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    ACTION_TYPE_FIELD_NUMBER: _builtins.int
    ACTION_CONTEXT_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    CREATOR_ID_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    event_type: _builtins.str
    attached_entity_type: _builtins.str
    """Required scope anchor.  The rule fires only for events
    whose primary entity matches this anchor (or, in the
    directory / shelf case, a descendant / contained book of
    it).  Global rules are no longer supported.
    "directory" | "note" | "shelf"
    """
    attached_entity_id: _builtins.str
    action_type: _builtins.str
    """Action split into a discriminator + parameters so the
    discriminator is indexable and round-trips cleanly.
    "add_to_directory" | "add_tag" | ...
    """
    enabled: _builtins.bool
    creator_id: _builtins.str
    @_builtins.property
    def condition(self) -> _struct_pb2.Struct:
        """Condition dataclass, serialised as a Struct:
          { "type": "note_content_contains", "substring": "linux" }
        """

    @_builtins.property
    def action_context(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        event_type: _builtins.str = ...,
        attached_entity_type: _builtins.str = ...,
        attached_entity_id: _builtins.str = ...,
        condition: _struct_pb2.Struct | None = ...,
        action_type: _builtins.str = ...,
        action_context: _struct_pb2.Struct | None = ...,
        enabled: _builtins.bool = ...,
        creator_id: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action_context", b"action_context", "condition", b"condition", "created_at", b"created_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_context", b"action_context", "action_type", b"action_type", "attached_entity_id", b"attached_entity_id", "attached_entity_type", b"attached_entity_type", "condition", b"condition", "created_at", b"created_at", "creator_id", b"creator_id", "enabled", b"enabled", "event_type", b"event_type", "id", b"id", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Rule: _TypeAlias = Rule  # noqa: Y015

@_typing.final
class RuleFilter(_message.Message):
    """Used by GetRules to scope the list.  All fields optional."""

    DESCRIPTOR: _descriptor.Descriptor

    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_ID_FIELD_NUMBER: _builtins.int
    ENABLED_ONLY_FIELD_NUMBER: _builtins.int
    CREATOR_ID_FIELD_NUMBER: _builtins.int
    event_type: _builtins.str
    attached_entity_type: _builtins.str
    """"directory" | "note" | "shelf" """
    attached_entity_id: _builtins.str
    enabled_only: _builtins.bool
    creator_id: _builtins.str
    def __init__(
        self,
        *,
        event_type: _builtins.str = ...,
        attached_entity_type: _builtins.str = ...,
        attached_entity_id: _builtins.str = ...,
        enabled_only: _builtins.bool = ...,
        creator_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attached_entity_id", b"attached_entity_id", "attached_entity_type", b"attached_entity_type", "creator_id", b"creator_id", "enabled_only", b"enabled_only", "event_type", b"event_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RuleFilter: _TypeAlias = RuleFilter  # noqa: Y015

@_typing.final
class CreateRuleRequest(_message.Message):
    """===== Requests ==========================================================="""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_ID_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    ACTION_TYPE_FIELD_NUMBER: _builtins.int
    ACTION_CONTEXT_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    CREATOR_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    event_type: _builtins.str
    attached_entity_type: _builtins.str
    attached_entity_id: _builtins.str
    action_type: _builtins.str
    enabled: _builtins.bool
    creator_id: _builtins.str
    """creator_id defaults to user_id when unset."""
    @_builtins.property
    def condition(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def action_context(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        event_type: _builtins.str = ...,
        attached_entity_type: _builtins.str = ...,
        attached_entity_id: _builtins.str = ...,
        condition: _struct_pb2.Struct | None = ...,
        action_type: _builtins.str = ...,
        action_context: _struct_pb2.Struct | None = ...,
        enabled: _builtins.bool | None = ...,
        creator_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "action_context", b"action_context", "condition", b"condition", "enabled", b"enabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "action_context", b"action_context", "action_type", b"action_type", "attached_entity_id", b"attached_entity_id", "attached_entity_type", b"attached_entity_type", "condition", b"condition", "creator_id", b"creator_id", "enabled", b"enabled", "event_type", b"event_type", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__enabled: _TypeAlias = _typing.Literal["enabled"]  # noqa: Y015
    _WhichOneofArgType__enabled: _TypeAlias = _typing.Literal["_enabled", b"_enabled"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enabled) -> _WhichOneofReturnType__enabled | None: ...

Global___CreateRuleRequest: _TypeAlias = CreateRuleRequest  # noqa: Y015

@_typing.final
class GetRuleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRuleRequest: _TypeAlias = GetRuleRequest  # noqa: Y015

@_typing.final
class GetRulesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    @_builtins.property
    def filter(self) -> Global___RuleFilter: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        filter: Global___RuleFilter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRulesRequest: _TypeAlias = GetRulesRequest  # noqa: Y015

@_typing.final
class UpdateRuleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_TYPE_FIELD_NUMBER: _builtins.int
    ATTACHED_ENTITY_ID_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    ACTION_TYPE_FIELD_NUMBER: _builtins.int
    ACTION_CONTEXT_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    id: _builtins.str
    event_type: _builtins.str
    attached_entity_type: _builtins.str
    attached_entity_id: _builtins.str
    action_type: _builtins.str
    enabled: _builtins.bool
    @_builtins.property
    def condition(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def action_context(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        id: _builtins.str = ...,
        event_type: _builtins.str | None = ...,
        attached_entity_type: _builtins.str | None = ...,
        attached_entity_id: _builtins.str | None = ...,
        condition: _struct_pb2.Struct | None = ...,
        action_type: _builtins.str | None = ...,
        action_context: _struct_pb2.Struct | None = ...,
        enabled: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_action_type", b"_action_type", "_attached_entity_id", b"_attached_entity_id", "_attached_entity_type", b"_attached_entity_type", "_enabled", b"_enabled", "_event_type", b"_event_type", "action_context", b"action_context", "action_type", b"action_type", "attached_entity_id", b"attached_entity_id", "attached_entity_type", b"attached_entity_type", "condition", b"condition", "enabled", b"enabled", "event_type", b"event_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_action_type", b"_action_type", "_attached_entity_id", b"_attached_entity_id", "_attached_entity_type", b"_attached_entity_type", "_enabled", b"_enabled", "_event_type", b"_event_type", "action_context", b"action_context", "action_type", b"action_type", "attached_entity_id", b"attached_entity_id", "attached_entity_type", b"attached_entity_type", "condition", b"condition", "enabled", b"enabled", "event_type", b"event_type", "id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__action_type: _TypeAlias = _typing.Literal["action_type"]  # noqa: Y015
    _WhichOneofArgType__action_type: _TypeAlias = _typing.Literal["_action_type", b"_action_type"]  # noqa: Y015
    _WhichOneofReturnType__attached_entity_id: _TypeAlias = _typing.Literal["attached_entity_id"]  # noqa: Y015
    _WhichOneofArgType__attached_entity_id: _TypeAlias = _typing.Literal["_attached_entity_id", b"_attached_entity_id"]  # noqa: Y015
    _WhichOneofReturnType__attached_entity_type: _TypeAlias = _typing.Literal["attached_entity_type"]  # noqa: Y015
    _WhichOneofArgType__attached_entity_type: _TypeAlias = _typing.Literal["_attached_entity_type", b"_attached_entity_type"]  # noqa: Y015
    _WhichOneofReturnType__enabled: _TypeAlias = _typing.Literal["enabled"]  # noqa: Y015
    _WhichOneofArgType__enabled: _TypeAlias = _typing.Literal["_enabled", b"_enabled"]  # noqa: Y015
    _WhichOneofReturnType__event_type: _TypeAlias = _typing.Literal["event_type"]  # noqa: Y015
    _WhichOneofArgType__event_type: _TypeAlias = _typing.Literal["_event_type", b"_event_type"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__action_type) -> _WhichOneofReturnType__action_type | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__attached_entity_id) -> _WhichOneofReturnType__attached_entity_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__attached_entity_type) -> _WhichOneofReturnType__attached_entity_type | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enabled) -> _WhichOneofReturnType__enabled | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__event_type) -> _WhichOneofReturnType__event_type | None: ...

Global___UpdateRuleRequest: _TypeAlias = UpdateRuleRequest  # noqa: Y015

@_typing.final
class DeleteRuleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteRuleRequest: _TypeAlias = DeleteRuleRequest  # noqa: Y015

@_typing.final
class CreateRuleResponse(_message.Message):
    """===== Responses =========================================================="""

    DESCRIPTOR: _descriptor.Descriptor

    RULE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rule(self) -> Global___Rule: ...
    def __init__(
        self,
        *,
        rule: Global___Rule | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["rule", b"rule"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rule", b"rule"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateRuleResponse: _TypeAlias = CreateRuleResponse  # noqa: Y015

@_typing.final
class GetRuleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rule(self) -> Global___Rule: ...
    def __init__(
        self,
        *,
        rule: Global___Rule | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["rule", b"rule"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rule", b"rule"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRuleResponse: _TypeAlias = GetRuleResponse  # noqa: Y015

@_typing.final
class GetRulesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___Rule]: ...
    def __init__(
        self,
        *,
        rules: _abc.Iterable[Global___Rule] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rules", b"rules"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetRulesResponse: _TypeAlias = GetRulesResponse  # noqa: Y015

@_typing.final
class UpdateRuleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rule(self) -> Global___Rule: ...
    def __init__(
        self,
        *,
        rule: Global___Rule | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["rule", b"rule"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rule", b"rule"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateRuleResponse: _TypeAlias = UpdateRuleResponse  # noqa: Y015

@_typing.final
class DeleteRuleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EMPTY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def empty(self) -> _empty_pb2.Empty:
        """Empty for now; kept so the response shape can grow
        without breaking clients.
        """

    def __init__(
        self,
        *,
        empty: _empty_pb2.Empty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["empty", b"empty"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["empty", b"empty"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteRuleResponse: _TypeAlias = DeleteRuleResponse  # noqa: Y015
