# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc_mod.proto import sharing_pb2 as src_dot_grpc__mod_dot_proto_dot_sharing__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc_mod/proto/sharing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SharingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateShare = channel.unary_unary(
                '/proto.SharingService/CreateShare',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.CreateShareRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
                _registered_method=True)
        self.UpdateShare = channel.unary_unary(
                '/proto.SharingService/UpdateShare',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.UpdateShareRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
                _registered_method=True)
        self.GetSharesById = channel.unary_stream(
                '/proto.SharingService/GetSharesById',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.GetSharesByIdRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
                _registered_method=True)
        self.GetShares = channel.unary_stream(
                '/proto.SharingService/GetShares',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.GetSharesRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
                _registered_method=True)
        self.DeleteShares = channel.unary_unary(
                '/proto.SharingService/DeleteShares',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.DeleteSharesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AccessShare = channel.unary_unary(
                '/proto.SharingService/AccessShare',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.AccessShareRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.AccessShareResponse.FromString,
                _registered_method=True)


class SharingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSharesById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShares(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShares(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccessShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SharingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateShare': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShare,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.CreateShareRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.SerializeToString,
            ),
            'UpdateShare': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShare,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.UpdateShareRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.SerializeToString,
            ),
            'GetSharesById': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSharesById,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.GetSharesByIdRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.SerializeToString,
            ),
            'GetShares': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShares,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.GetSharesRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.SerializeToString,
            ),
            'DeleteShares': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShares,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.DeleteSharesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AccessShare': grpc.unary_unary_rpc_method_handler(
                    servicer.AccessShare,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.AccessShareRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_sharing__pb2.AccessShareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SharingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SharingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SharingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SharingService/CreateShare',
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.CreateShareRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SharingService/UpdateShare',
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.UpdateShareRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSharesById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.SharingService/GetSharesById',
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.GetSharesByIdRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShares(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.SharingService/GetShares',
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.GetSharesRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.NoteShare.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteShares(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SharingService/DeleteShares',
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.DeleteSharesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccessShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SharingService/AccessShare',
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.AccessShareRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_sharing__pb2.AccessShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
