"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SharePermission:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SharePermissionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SharePermission.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SHARE_PERMISSION_UNSPECIFIED: _SharePermission.ValueType  # 0
    SHARE_PERMISSION_READ: _SharePermission.ValueType  # 1
    SHARE_PERMISSION_WRITE: _SharePermission.ValueType  # 2

class SharePermission(_SharePermission, metaclass=_SharePermissionEnumTypeWrapper):
    """the permission a share can have"""

SHARE_PERMISSION_UNSPECIFIED: SharePermission.ValueType  # 0
SHARE_PERMISSION_READ: SharePermission.ValueType  # 1
SHARE_PERMISSION_WRITE: SharePermission.ValueType  # 2
Global___SharePermission: _TypeAlias = SharePermission  # noqa: Y015

@_typing.final
class NullableString(_message.Message):
    """String value wrapper for fields where the API needs to distinguish:
    - field omitted: leave unchanged / do not filter
    - null_value=true: explicitly set or search for NULL
    - value set: use the provided string
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    NULL_VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    null_value: _builtins.bool
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
        null_value: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kind", b"kind", "null_value", b"null_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kind", b"kind", "null_value", b"null_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["value", "null_value"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___NullableString: _TypeAlias = NullableString  # noqa: Y015

@_typing.final
class NullableTimestamp(_message.Message):
    """Timestamp value wrapper for fields where the API needs to distinguish:
    - field omitted: leave unchanged / do not filter
    - null_value=true: explicitly set or search for NULL
    - value set: use the provided timestamp
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    NULL_VALUE_FIELD_NUMBER: _builtins.int
    null_value: _builtins.bool
    @_builtins.property
    def value(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        value: _timestamp_pb2.Timestamp | None = ...,
        null_value: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kind", b"kind", "null_value", b"null_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kind", b"kind", "null_value", b"null_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["value", "null_value"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___NullableTimestamp: _TypeAlias = NullableTimestamp  # noqa: Y015

@_typing.final
class NoteShare(_message.Message):
    """A persisted share entry for a note."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    NOTE_ID_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    CREATED_BY_FIELD_NUMBER: _builtins.int
    ONLINE_SINCE_FIELD_NUMBER: _builtins.int
    ONLINE_UNTIL_FIELD_NUMBER: _builtins.int
    PERMISSION_FIELD_NUMBER: _builtins.int
    ACCESS_AS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    note_id: _builtins.str
    created_by: _builtins.str
    permission: Global___SharePermission.ValueType
    access_as: _builtins.str
    @_builtins.property
    def description(self) -> Global___NullableString: ...
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def online_since(self) -> Global___NullableTimestamp: ...
    @_builtins.property
    def online_until(self) -> Global___NullableTimestamp: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        description: Global___NullableString | None = ...,
        note_id: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        created_by: _builtins.str = ...,
        online_since: Global___NullableTimestamp | None = ...,
        online_until: Global___NullableTimestamp | None = ...,
        permission: Global___SharePermission.ValueType = ...,
        access_as: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "description", b"description", "online_since", b"online_since", "online_until", b"online_until"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_as", b"access_as", "created_at", b"created_at", "created_by", b"created_by", "description", b"description", "id", b"id", "note_id", b"note_id", "online_since", b"online_since", "online_until", b"online_until", "permission", b"permission"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NoteShare: _TypeAlias = NoteShare  # noqa: Y015

@_typing.final
class ShareFilter(_message.Message):
    """Filter for searching shares.

    Date values are evaluated inclusively:
    - online_since.value finds shares with online_since >= value
    - online_until.value finds shares with online_until <= value
    - null_value=true searches for rows where the date column is NULL
    """

    DESCRIPTOR: _descriptor.Descriptor

    NOTE_ID_FIELD_NUMBER: _builtins.int
    CREATED_BY_FIELD_NUMBER: _builtins.int
    ONLINE_SINCE_FIELD_NUMBER: _builtins.int
    ONLINE_UNTIL_FIELD_NUMBER: _builtins.int
    note_id: _builtins.str
    created_by: _builtins.str
    @_builtins.property
    def online_since(self) -> Global___NullableTimestamp: ...
    @_builtins.property
    def online_until(self) -> Global___NullableTimestamp: ...
    def __init__(
        self,
        *,
        note_id: _builtins.str | None = ...,
        created_by: _builtins.str | None = ...,
        online_since: Global___NullableTimestamp | None = ...,
        online_until: Global___NullableTimestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_created_by", b"_created_by", "_note_id", b"_note_id", "created_by", b"created_by", "note_id", b"note_id", "online_since", b"online_since", "online_until", b"online_until"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_created_by", b"_created_by", "_note_id", b"_note_id", "created_by", b"created_by", "note_id", b"note_id", "online_since", b"online_since", "online_until", b"online_until"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__created_by: _TypeAlias = _typing.Literal["created_by"]  # noqa: Y015
    _WhichOneofArgType__created_by: _TypeAlias = _typing.Literal["_created_by", b"_created_by"]  # noqa: Y015
    _WhichOneofReturnType__note_id: _TypeAlias = _typing.Literal["note_id"]  # noqa: Y015
    _WhichOneofArgType__note_id: _TypeAlias = _typing.Literal["_note_id", b"_note_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__created_by) -> _WhichOneofReturnType__created_by | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__note_id) -> _WhichOneofReturnType__note_id | None: ...

Global___ShareFilter: _TypeAlias = ShareFilter  # noqa: Y015

@_typing.final
class CreateShareRequest(_message.Message):
    """Create one share. The requester user_id is used for permission checks."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    NOTE_ID_FIELD_NUMBER: _builtins.int
    ONLINE_SINCE_FIELD_NUMBER: _builtins.int
    ONLINE_UNTIL_FIELD_NUMBER: _builtins.int
    PERMISSION_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    note_id: _builtins.str
    permission: Global___SharePermission.ValueType
    @_builtins.property
    def description(self) -> Global___NullableString: ...
    @_builtins.property
    def online_since(self) -> Global___NullableTimestamp: ...
    @_builtins.property
    def online_until(self) -> Global___NullableTimestamp: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        description: Global___NullableString | None = ...,
        note_id: _builtins.str = ...,
        online_since: Global___NullableTimestamp | None = ...,
        online_until: Global___NullableTimestamp | None = ...,
        permission: Global___SharePermission.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "online_since", b"online_since", "online_until", b"online_until"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "note_id", b"note_id", "online_since", b"online_since", "online_until", b"online_until", "permission", b"permission", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateShareRequest: _TypeAlias = CreateShareRequest  # noqa: Y015

@_typing.final
class AccessShareRequest(_message.Message):
    """Access a share by its ID. This ID is part of the share URL /public/n/<share_id>"""

    DESCRIPTOR: _descriptor.Descriptor

    SHARE_ID_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AccessShareRequest: _TypeAlias = AccessShareRequest  # noqa: Y015

@_typing.final
class AccessShareResponse(_message.Message):
    """Response for an access share request, containing the note associated with the share"""

    DESCRIPTOR: _descriptor.Descriptor

    SHARE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def share(self) -> Global___NoteShare: ...
    def __init__(
        self,
        *,
        share: Global___NoteShare | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["share", b"share"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["share", b"share"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AccessShareResponse: _TypeAlias = AccessShareResponse  # noqa: Y015

@_typing.final
class GetShareUserRequest(_message.Message):
    """request with share id to get the temporary user id that can be used to access the share."""

    DESCRIPTOR: _descriptor.Descriptor

    SHARE_ID_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetShareUserRequest: _TypeAlias = GetShareUserRequest  # noqa: Y015

@_typing.final
class GetShareUserResponse(_message.Message):
    """Response for a get share user request, containing the temporary user id"""

    DESCRIPTOR: _descriptor.Descriptor

    ACCESS_AS_FIELD_NUMBER: _builtins.int
    ONLINE_UNTIL_FIELD_NUMBER: _builtins.int
    access_as: _builtins.str
    @_builtins.property
    def online_until(self) -> Global___NullableTimestamp: ...
    def __init__(
        self,
        *,
        access_as: _builtins.str = ...,
        online_until: Global___NullableTimestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["online_until", b"online_until"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_as", b"access_as", "online_until", b"online_until"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetShareUserResponse: _TypeAlias = GetShareUserResponse  # noqa: Y015

@_typing.final
class UpdateShareRequest(_message.Message):
    """Update one share. Only fields present on share should be updated.
    The requester user_id is used for permission checks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    SHARE_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    @_builtins.property
    def share(self) -> Global___NoteShare: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        share: Global___NoteShare | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["share", b"share"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["share", b"share", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateShareRequest: _TypeAlias = UpdateShareRequest  # noqa: Y015

@_typing.final
class GetSharesByIdRequest(_message.Message):
    """Fetch shares by their exact share IDs.
    The requester user_id is used for permission checks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    SHARE_IDS_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    @_builtins.property
    def share_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        share_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["share_ids", b"share_ids", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSharesByIdRequest: _TypeAlias = GetSharesByIdRequest  # noqa: Y015

@_typing.final
class GetSharesRequest(_message.Message):
    """Fetch shares matching a filter.
    The requester user_id is used for permission checks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    @_builtins.property
    def filter(self) -> Global___ShareFilter: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        filter: Global___ShareFilter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSharesRequest: _TypeAlias = GetSharesRequest  # noqa: Y015

@_typing.final
class DeleteSharesRequest(_message.Message):
    """Delete shares by their exact share IDs.
    The requester user_id is used for permission checks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    SHARE_IDS_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    @_builtins.property
    def share_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        share_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["share_ids", b"share_ids", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteSharesRequest: _TypeAlias = DeleteSharesRequest  # noqa: Y015
