# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc_mod.proto import shelf_pb2 as src_dot_grpc__mod_dot_proto_dot_shelf__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc_mod/proto/shelf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShelfServiceStub:
    """===== Service ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShelf = channel.unary_unary(
                '/proto.ShelfService/GetShelf',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelfRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfResponse.FromString,
                _registered_method=True)
        self.GetShelves = channel.unary_unary(
                '/proto.ShelfService/GetShelves',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelvesRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelvesResponse.FromString,
                _registered_method=True)
        self.ListShelves = channel.unary_unary(
                '/proto.ShelfService/ListShelves',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ListShelvesRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelvesResponse.FromString,
                _registered_method=True)
        self.CreateShelf = channel.unary_unary(
                '/proto.ShelfService/CreateShelf',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.CreateShelfRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.CreateShelfResponse.FromString,
                _registered_method=True)
        self.UpdateShelf = channel.unary_unary(
                '/proto.ShelfService/UpdateShelf',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.UpdateShelfRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfResponse.FromString,
                _registered_method=True)
        self.DeleteShelf = channel.unary_unary(
                '/proto.ShelfService/DeleteShelf',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DeleteShelfRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DeleteShelfResponse.FromString,
                _registered_method=True)
        self.SetBooks = channel.unary_unary(
                '/proto.ShelfService/SetBooks',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.SetBooksRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AttachBook = channel.unary_unary(
                '/proto.ShelfService/AttachBook',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.AttachBookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DetachBook = channel.unary_unary(
                '/proto.ShelfService/DetachBook',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DetachBookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetBooksOfShelf = channel.unary_unary(
                '/proto.ShelfService/GetBooksOfShelf',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetBooksOfShelfRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.BooksResponse.FromString,
                _registered_method=True)
        self.GetShelvesOfBook = channel.unary_unary(
                '/proto.ShelfService/GetShelvesOfBook',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelvesOfBookRequest.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfIdsResponse.FromString,
                _registered_method=True)


class ShelfServiceServicer:
    """===== Service ============================================================

    """

    def GetShelf(self, request, context):
        """CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShelves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShelves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateShelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBooks(self, request, context):
        """Book bindings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetachBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksOfShelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShelvesOfBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShelfServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShelf': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShelf,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelfRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfResponse.SerializeToString,
            ),
            'GetShelves': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShelves,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelvesRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelvesResponse.SerializeToString,
            ),
            'ListShelves': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShelves,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ListShelvesRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelvesResponse.SerializeToString,
            ),
            'CreateShelf': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShelf,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.CreateShelfRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.CreateShelfResponse.SerializeToString,
            ),
            'UpdateShelf': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShelf,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.UpdateShelfRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfResponse.SerializeToString,
            ),
            'DeleteShelf': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShelf,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DeleteShelfRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DeleteShelfResponse.SerializeToString,
            ),
            'SetBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBooks,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.SetBooksRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AttachBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachBook,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.AttachBookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DetachBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DetachBook,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DetachBookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBooksOfShelf': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksOfShelf,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetBooksOfShelfRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.BooksResponse.SerializeToString,
            ),
            'GetShelvesOfBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShelvesOfBook,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelvesOfBookRequest.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfIdsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ShelfService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ShelfService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShelfService:
    """===== Service ============================================================

    """

    @staticmethod
    def GetShelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/GetShelf',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelfRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShelves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/GetShelves',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelvesRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelvesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShelves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/ListShelves',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ListShelvesRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelvesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateShelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/CreateShelf',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.CreateShelfRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.CreateShelfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateShelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/UpdateShelf',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.UpdateShelfRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteShelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/DeleteShelf',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DeleteShelfRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DeleteShelfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/SetBooks',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.SetBooksRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/AttachBook',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.AttachBookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetachBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/DetachBook',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.DetachBookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooksOfShelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/GetBooksOfShelf',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetBooksOfShelfRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.BooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShelvesOfBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ShelfService/GetShelvesOfBook',
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.GetShelvesOfBookRequest.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_shelf__pb2.ShelfIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
