# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_mod.proto import thirdparty_migrations_pb2 as src_dot_grpc__mod_dot_proto_dot_thirdparty__migrations__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc_mod/proto/thirdparty_migrations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ThirdpartyMigrationsServiceStub:
    """Service that imports content from third-party documentation tools
    into the project's directory / note / attachment model.

    Only the BookStack book import is implemented today; further RPCs
    will be added here for other sources (Notion, Confluence, ...).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookstackBookImport = channel.stream_unary(
                '/proto.ThirdpartyMigrationsService/BookstackBookImport',
                request_serializer=src_dot_grpc__mod_dot_proto_dot_thirdparty__migrations__pb2.BookstackBookImportChunk.SerializeToString,
                response_deserializer=src_dot_grpc__mod_dot_proto_dot_thirdparty__migrations__pb2.BookstackBookImportResponse.FromString,
                _registered_method=True)


class ThirdpartyMigrationsServiceServicer:
    """Service that imports content from third-party documentation tools
    into the project's directory / note / attachment model.

    Only the BookStack book import is implemented today; further RPCs
    will be added here for other sources (Notion, Confluence, ...).
    """

    def BookstackBookImport(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ThirdpartyMigrationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookstackBookImport': grpc.stream_unary_rpc_method_handler(
                    servicer.BookstackBookImport,
                    request_deserializer=src_dot_grpc__mod_dot_proto_dot_thirdparty__migrations__pb2.BookstackBookImportChunk.FromString,
                    response_serializer=src_dot_grpc__mod_dot_proto_dot_thirdparty__migrations__pb2.BookstackBookImportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ThirdpartyMigrationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ThirdpartyMigrationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ThirdpartyMigrationsService:
    """Service that imports content from third-party documentation tools
    into the project's directory / note / attachment model.

    Only the BookStack book import is implemented today; further RPCs
    will be added here for other sources (Notion, Confluence, ...).
    """

    @staticmethod
    def BookstackBookImport(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/proto.ThirdpartyMigrationsService/BookstackBookImport',
            src_dot_grpc__mod_dot_proto_dot_thirdparty__migrations__pb2.BookstackBookImportChunk.SerializeToString,
            src_dot_grpc__mod_dot_proto_dot_thirdparty__migrations__pb2.BookstackBookImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
