# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/grpc_mod/proto/thirdparty_migrations.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'src/grpc_mod/proto/thirdparty_migrations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.src/grpc_mod/proto/thirdparty_migrations.proto\x12\x05proto\"<\n\x18\x42ookstackBookImportChunk\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"^\n\x18\x42ookstackImportedChapter\x12\x14\n\x0c\x64irectory_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63hapter_name\x18\x02 \x01(\t\x12\x16\n\x0epages_imported\x18\x03 \x01(\x05\"\xa1\x01\n\x1b\x42ookstackBookImportResponse\x12\x19\n\x11\x62ook_directory_id\x18\x01 \x01(\t\x12\x31\n\x08\x63hapters\x18\x02 \x03(\x0b\x32\x1f.proto.BookstackImportedChapter\x12\x16\n\x0epages_imported\x18\x03 \x01(\x05\x12\x1c\n\x14\x61ttachments_uploaded\x18\x04 \x01(\x05\x32{\n\x1bThirdpartyMigrationsService\x12\\\n\x13\x42ookstackBookImport\x12\x1f.proto.BookstackBookImportChunk\x1a\".proto.BookstackBookImportResponse(\x01\x42\x31Z/github.com/KuramaSyu/Wersu-Rest/src/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc_mod.proto.thirdparty_migrations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/KuramaSyu/Wersu-Rest/src/proto;proto'
  _globals['_BOOKSTACKBOOKIMPORTCHUNK']._serialized_start=57
  _globals['_BOOKSTACKBOOKIMPORTCHUNK']._serialized_end=117
  _globals['_BOOKSTACKIMPORTEDCHAPTER']._serialized_start=119
  _globals['_BOOKSTACKIMPORTEDCHAPTER']._serialized_end=213
  _globals['_BOOKSTACKBOOKIMPORTRESPONSE']._serialized_start=216
  _globals['_BOOKSTACKBOOKIMPORTRESPONSE']._serialized_end=377
  _globals['_THIRDPARTYMIGRATIONSSERVICE']._serialized_start=379
  _globals['_THIRDPARTYMIGRATIONSSERVICE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
