"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BookstackBookImportChunk(_message.Message):
    """One chunk of a streamed BookStack book zip. The first chunk in the
    stream carries `user_id`; subsequent chunks may leave it empty.

    `content` holds raw bytes of the zip (or a slice of them when the
    client chooses to chunk the upload).
    """

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    content: _builtins.bytes
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BookstackBookImportChunk: _TypeAlias = BookstackBookImportChunk  # noqa: Y015

@_typing.final
class BookstackImportedChapter(_message.Message):
    """One chapter directory that was created during the import."""

    DESCRIPTOR: _descriptor.Descriptor

    DIRECTORY_ID_FIELD_NUMBER: _builtins.int
    CHAPTER_NAME_FIELD_NUMBER: _builtins.int
    PAGES_IMPORTED_FIELD_NUMBER: _builtins.int
    directory_id: _builtins.str
    chapter_name: _builtins.str
    pages_imported: _builtins.int
    def __init__(
        self,
        *,
        directory_id: _builtins.str = ...,
        chapter_name: _builtins.str = ...,
        pages_imported: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chapter_name", b"chapter_name", "directory_id", b"directory_id", "pages_imported", b"pages_imported"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BookstackImportedChapter: _TypeAlias = BookstackImportedChapter  # noqa: Y015

@_typing.final
class BookstackBookImportResponse(_message.Message):
    """Result returned once the BookStack book zip has been fully imported."""

    DESCRIPTOR: _descriptor.Descriptor

    BOOK_DIRECTORY_ID_FIELD_NUMBER: _builtins.int
    CHAPTERS_FIELD_NUMBER: _builtins.int
    PAGES_IMPORTED_FIELD_NUMBER: _builtins.int
    ATTACHMENTS_UPLOADED_FIELD_NUMBER: _builtins.int
    book_directory_id: _builtins.str
    pages_imported: _builtins.int
    attachments_uploaded: _builtins.int
    @_builtins.property
    def chapters(self) -> _containers.RepeatedCompositeFieldContainer[Global___BookstackImportedChapter]: ...
    def __init__(
        self,
        *,
        book_directory_id: _builtins.str = ...,
        chapters: _abc.Iterable[Global___BookstackImportedChapter] | None = ...,
        pages_imported: _builtins.int = ...,
        attachments_uploaded: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attachments_uploaded", b"attachments_uploaded", "book_directory_id", b"book_directory_id", "chapters", b"chapters", "pages_imported", b"pages_imported"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BookstackBookImportResponse: _TypeAlias = BookstackBookImportResponse  # noqa: Y015
