"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class User(_message.Message):
    """User Messages"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DISCORD_ID_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    DISCRIMINATOR_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    discord_id: _builtins.int
    avatar: _builtins.str
    username: _builtins.str
    discriminator: _builtins.str
    email: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        discord_id: _builtins.int = ...,
        avatar: _builtins.str = ...,
        username: _builtins.str = ...,
        discriminator: _builtins.str = ...,
        email: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "discord_id", b"discord_id", "discriminator", b"discriminator", "email", b"email", "id", b"id", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015

@_typing.final
class GetUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DISCORD_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    discord_id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.str | None = ...,
        discord_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_discord_id", b"_discord_id", "_id", b"_id", "discord_id", b"discord_id", "id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_discord_id", b"_discord_id", "_id", b"_id", "discord_id", b"discord_id", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__discord_id: _TypeAlias = _typing.Literal["discord_id"]  # noqa: Y015
    _WhichOneofArgType__discord_id: _TypeAlias = _typing.Literal["_discord_id", b"_discord_id"]  # noqa: Y015
    _WhichOneofReturnType__id: _TypeAlias = _typing.Literal["id"]  # noqa: Y015
    _WhichOneofArgType__id: _TypeAlias = _typing.Literal["_id", b"_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__discord_id) -> _WhichOneofReturnType__discord_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__id) -> _WhichOneofReturnType__id | None: ...

Global___GetUserRequest: _TypeAlias = GetUserRequest  # noqa: Y015

@_typing.final
class PostUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISCORD_ID_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    DISCRIMINATOR_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    discord_id: _builtins.int
    avatar: _builtins.str
    username: _builtins.str
    discriminator: _builtins.str
    email: _builtins.str
    def __init__(
        self,
        *,
        discord_id: _builtins.int = ...,
        avatar: _builtins.str = ...,
        username: _builtins.str = ...,
        discriminator: _builtins.str = ...,
        email: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "discord_id", b"discord_id", "discriminator", b"discriminator", "email", b"email", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PostUserRequest: _TypeAlias = PostUserRequest  # noqa: Y015

@_typing.final
class AlterUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DISCORD_ID_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    DISCRIMINATOR_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    discord_id: _builtins.int
    avatar: _builtins.str
    username: _builtins.str
    discriminator: _builtins.str
    email: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        discord_id: _builtins.int | None = ...,
        avatar: _builtins.str | None = ...,
        username: _builtins.str | None = ...,
        discriminator: _builtins.str | None = ...,
        email: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_avatar", b"_avatar", "_discord_id", b"_discord_id", "_discriminator", b"_discriminator", "_email", b"_email", "_username", b"_username", "avatar", b"avatar", "discord_id", b"discord_id", "discriminator", b"discriminator", "email", b"email", "username", b"username"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_avatar", b"_avatar", "_discord_id", b"_discord_id", "_discriminator", b"_discriminator", "_email", b"_email", "_username", b"_username", "avatar", b"avatar", "discord_id", b"discord_id", "discriminator", b"discriminator", "email", b"email", "id", b"id", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__avatar: _TypeAlias = _typing.Literal["avatar"]  # noqa: Y015
    _WhichOneofArgType__avatar: _TypeAlias = _typing.Literal["_avatar", b"_avatar"]  # noqa: Y015
    _WhichOneofReturnType__discord_id: _TypeAlias = _typing.Literal["discord_id"]  # noqa: Y015
    _WhichOneofArgType__discord_id: _TypeAlias = _typing.Literal["_discord_id", b"_discord_id"]  # noqa: Y015
    _WhichOneofReturnType__discriminator: _TypeAlias = _typing.Literal["discriminator"]  # noqa: Y015
    _WhichOneofArgType__discriminator: _TypeAlias = _typing.Literal["_discriminator", b"_discriminator"]  # noqa: Y015
    _WhichOneofReturnType__email: _TypeAlias = _typing.Literal["email"]  # noqa: Y015
    _WhichOneofArgType__email: _TypeAlias = _typing.Literal["_email", b"_email"]  # noqa: Y015
    _WhichOneofReturnType__username: _TypeAlias = _typing.Literal["username"]  # noqa: Y015
    _WhichOneofArgType__username: _TypeAlias = _typing.Literal["_username", b"_username"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__avatar) -> _WhichOneofReturnType__avatar | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__discord_id) -> _WhichOneofReturnType__discord_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__discriminator) -> _WhichOneofReturnType__discriminator | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__email) -> _WhichOneofReturnType__email | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__username) -> _WhichOneofReturnType__username | None: ...

Global___AlterUserRequest: _TypeAlias = AlterUserRequest  # noqa: Y015

@_typing.final
class DeleteUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteUserRequest: _TypeAlias = DeleteUserRequest  # noqa: Y015

@_typing.final
class DeleteUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteUserResponse: _TypeAlias = DeleteUserResponse  # noqa: Y015
