# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_mod/proto/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_mod/proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpc_mod/proto/user.proto\x12\x04user\":\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ndiscord_id\x18\x02 \x01(\x03\x12\x12\n\navatar_url\x18\x03 \x01(\t\"P\n\x0eGetUserRequest\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x17\n\ndiscord_id\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x05\n\x03_idB\r\n\x0b_discord_id\"9\n\x0fPostUserRequest\x12\x12\n\ndiscord_id\x18\x01 \x01(\x03\x12\x12\n\navatar_url\x18\x02 \x01(\t\"n\n\x10\x41lterUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\ndiscord_id\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\x17\n\navatar_url\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_discord_idB\r\n\x0b_avatar_url\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xdb\x01\n\x0bUserService\x12+\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\n.user.User\x12-\n\x08PostUser\x12\x15.user.PostUserRequest\x1a\n.user.User\x12/\n\tAlterUser\x12\x16.user.AlterUserRequest\x1a\n.user.User\x12?\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_mod.proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=35
  _globals['_USER']._serialized_end=93
  _globals['_GETUSERREQUEST']._serialized_start=95
  _globals['_GETUSERREQUEST']._serialized_end=175
  _globals['_POSTUSERREQUEST']._serialized_start=177
  _globals['_POSTUSERREQUEST']._serialized_end=234
  _globals['_ALTERUSERREQUEST']._serialized_start=236
  _globals['_ALTERUSERREQUEST']._serialized_end=346
  _globals['_DELETEUSERREQUEST']._serialized_start=348
  _globals['_DELETEUSERREQUEST']._serialized_end=379
  _globals['_DELETEUSERRESPONSE']._serialized_start=381
  _globals['_DELETEUSERRESPONSE']._serialized_end=418
  _globals['_USERSERVICE']._serialized_start=421
  _globals['_USERSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
