"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class User(google.protobuf.message.Message):
    """User Messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    DISCORD_ID_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    id: builtins.int
    discord_id: builtins.int
    avatar_url: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        discord_id: builtins.int = ...,
        avatar_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["avatar_url", b"avatar_url", "discord_id", b"discord_id", "id", b"id"]) -> None: ...

Global___User: typing_extensions.TypeAlias = User

@typing.final
class GetUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    DISCORD_ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    discord_id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        discord_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["discord_id", b"discord_id", "id", b"id"]) -> None: ...

Global___GetUserRequest: typing_extensions.TypeAlias = GetUserRequest

@typing.final
class PostUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISCORD_ID_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    discord_id: builtins.int
    avatar_url: builtins.str
    def __init__(
        self,
        *,
        discord_id: builtins.int = ...,
        avatar_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["avatar_url", b"avatar_url", "discord_id", b"discord_id"]) -> None: ...

Global___PostUserRequest: typing_extensions.TypeAlias = PostUserRequest

@typing.final
class AlterUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    DISCORD_ID_FIELD_NUMBER: builtins.int
    AVATAR_URL_FIELD_NUMBER: builtins.int
    id: builtins.int
    discord_id: builtins.int
    avatar_url: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        discord_id: builtins.int = ...,
        avatar_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["avatar_url", b"avatar_url", "discord_id", b"discord_id", "id", b"id"]) -> None: ...

Global___AlterUserRequest: typing_extensions.TypeAlias = AlterUserRequest

@typing.final
class DeleteUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

Global___DeleteUserRequest: typing_extensions.TypeAlias = DeleteUserRequest

@typing.final
class DeleteUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___DeleteUserResponse: typing_extensions.TypeAlias = DeleteUserResponse
